//HintName: HandlerOneDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class HandlerOneDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.SharedRequest,
            global::TestApp.HandlerOne.Response>
    {
        private readonly global::TestApp.HandlerOne _handler;

        public HandlerOneDispatcher(global::TestApp.HandlerOne handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.HandlerOne.Response>>
            Handle(global::TestApp.SharedRequest request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.HandlerOne.Response>.Success(response);
        }
    }
}
