//HintName: NoRequestHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class NoRequestHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            string,
            global::TestApp.NoRequestHandler.Response>
    {
        private readonly global::TestApp.NoRequestHandler _handler;

        public NoRequestHandlerDispatcher(global::TestApp.NoRequestHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.NoRequestHandler.Response>>
            Handle(string request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.NoRequestHandler.Response>.Success(response);
        }
    }
}
