//HintName: SyncHandleHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class SyncHandleHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.SyncHandleHandler.Request,
            global::TestApp.SyncHandleHandler.Response>
    {
        private readonly global::TestApp.SyncHandleHandler _handler;

        public SyncHandleHandlerDispatcher(global::TestApp.SyncHandleHandler handler)
        {
            _handler = handler;
        }

        public global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.SyncHandleHandler.Response>>
            Handle(global::TestApp.SyncHandleHandler.Request request)
        {
            var response = _handler.Handle(request);
            return global::System.Threading.Tasks.Task.FromResult(global::MiniBus.Convention.Result<global::TestApp.SyncHandleHandler.Response>.Success(response));
        }
    }
}
