//HintName: SimpleHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class SimpleHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.SimpleHandler.Request,
            global::TestApp.SimpleHandler.Response>
    {
        private readonly global::TestApp.SimpleHandler _handler;

        public SimpleHandlerDispatcher(global::TestApp.SimpleHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.SimpleHandler.Response>>
            Handle(global::TestApp.SimpleHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.SimpleHandler.Response>.Success(response);
        }
    }
}
