//HintName: ConventionRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus.Convention
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddScoped<global::TestApp.NoRequestHandler>();
            services.AddScoped<
                global::MiniBus.Convention.IConventionHandler<
                    string,
                    global::TestApp.NoRequestHandler.Response>,
                global::TestApp.NoRequestHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed ConventionBus extension methods ──────────────────────────────
    public static class ConventionBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::MiniBus.Convention.Result<global::TestApp.NoRequestHandler.Response>>
            Handle(this global::MiniBus.Convention.ConventionBus bus, string request)
            => bus.Handle<string, global::TestApp.NoRequestHandler.Response>(request);
    }
}
