//HintName: ExtHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class ExtHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.ExtHandler.Request,
            global::TestApp.ExtHandler.Response>
    {
        private readonly global::TestApp.ExtHandler _handler;

        public ExtHandlerDispatcher(global::TestApp.ExtHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.ExtHandler.Response>>
            Handle(global::TestApp.ExtHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.ExtHandler.Response>.Success(response);
        }
    }
}
