//HintName: OrderHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class OrderHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.OrderHandler.Request,
            global::TestApp.OrderHandler.Response>
    {
        private readonly global::TestApp.OrderHandler _handler;

        public OrderHandlerDispatcher(global::TestApp.OrderHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.OrderHandler.Response>>
            Handle(global::TestApp.OrderHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.OrderHandler.Response>.Success(response);
        }
    }
}
