//HintName: RegHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class RegHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.RegHandler.Request,
            global::TestApp.RegHandler.Response>
    {
        private readonly global::TestApp.RegHandler _handler;

        public RegHandlerDispatcher(global::TestApp.RegHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.RegHandler.Response>>
            Handle(global::TestApp.RegHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.RegHandler.Response>.Success(response);
        }
    }
}
