//HintName: ConventionRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus.Convention
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddScoped<global::TestApp.RegHandler>();
            services.AddScoped<
                global::MiniBus.Convention.IConventionHandler<
                    global::TestApp.RegHandler.Request,
                    global::TestApp.RegHandler.Response>,
                global::TestApp.RegHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed ConventionBus extension methods ──────────────────────────────
    public static class ConventionBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::MiniBus.Convention.Result<global::TestApp.RegHandler.Response>>
            Handle(this global::MiniBus.Convention.ConventionBus bus, global::TestApp.RegHandler.Request request)
            => bus.Handle<global::TestApp.RegHandler.Request, global::TestApp.RegHandler.Response>(request);
    }
}
