//HintName: HandlerBDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class HandlerBDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.HandlerB.Request,
            global::TestApp.HandlerB.Response>
    {
        private readonly global::TestApp.HandlerB _handler;

        public HandlerBDispatcher(global::TestApp.HandlerB handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.HandlerB.Response>>
            Handle(global::TestApp.HandlerB.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.HandlerB.Response>.Success(response);
        }
    }
}
