//HintName: ConventionRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus.Convention
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddScoped<global::TestApp.HandlerA>();
            services.AddScoped<
                global::MiniBus.Convention.IConventionHandler<
                    global::TestApp.HandlerA.Request,
                    global::TestApp.HandlerA.Response>,
                global::TestApp.HandlerADispatcher>();
            services.AddScoped<global::TestApp.HandlerB>();
            services.AddScoped<
                global::MiniBus.Convention.IConventionHandler<
                    global::TestApp.HandlerB.Request,
                    global::TestApp.HandlerB.Response>,
                global::TestApp.HandlerBDispatcher>();
            return services;
        }
    }

    // ── Typed ConventionBus extension methods ──────────────────────────────
    public static class ConventionBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::MiniBus.Convention.Result<global::TestApp.HandlerA.Response>>
            Handle(this global::MiniBus.Convention.ConventionBus bus, global::TestApp.HandlerA.Request request)
            => bus.Handle<global::TestApp.HandlerA.Request, global::TestApp.HandlerA.Response>(request);
        public static global::System.Threading.Tasks.Task<global::MiniBus.Convention.Result<global::TestApp.HandlerB.Response>>
            Handle(this global::MiniBus.Convention.ConventionBus bus, global::TestApp.HandlerB.Request request)
            => bus.Handle<global::TestApp.HandlerB.Request, global::TestApp.HandlerB.Response>(request);
    }
}
