//HintName: DummyHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class DummyHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.DummyHandler.Request,
            global::TestApp.DummyHandler.Response>
    {
        private readonly global::TestApp.DummyHandler _handler;

        public DummyHandlerDispatcher(global::TestApp.DummyHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.DummyHandler.Response>>
            Handle(global::TestApp.DummyHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.DummyHandler.Response>.Success(response);
        }
    }
}
