//HintName: BeforeConventionPipelineHandlerDispatcher_614fbc5e.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class BeforeConventionPipelineHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.BeforeConventionPipelineHandler.Request,
            global::TestApp.BeforeConventionPipelineHandler.Response>
    {
        private readonly global::TestApp.BeforeConventionPipelineHandler _handler;

        public BeforeConventionPipelineHandlerDispatcher(global::TestApp.BeforeConventionPipelineHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.BeforeConventionPipelineHandler);

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.BeforeConventionPipelineHandler.Response>>
            Handle(global::TestApp.BeforeConventionPipelineHandler.Request request)
        {
            var fromBeforeLoad = _handler.BeforeLoad(request);

            var fromNormalizeBefore = _handler.NormalizeBefore(fromBeforeLoad);

            var fromValidate = _handler.Validate(fromNormalizeBefore);
            if (!fromValidate.IsValid())
                return global::MiniBus.Result<global::TestApp.BeforeConventionPipelineHandler.Response>.Invalid(fromValidate);

            var fromHandle = await _handler.Handle(fromNormalizeBefore);
            return global::MiniBus.Result<global::TestApp.BeforeConventionPipelineHandler.Response>.Success(fromHandle);
        }
    }
}
