//HintName: HandlerBDispatcher_d55a38e5.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class HandlerBDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.HandlerB.Request,
            global::TestApp.HandlerB.Response>
    {
        private readonly global::TestApp.HandlerB _handler;

        public HandlerBDispatcher(global::TestApp.HandlerB handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.HandlerB);

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.HandlerB.Response>>
            Handle(global::TestApp.HandlerB.Request request)
        {
            var fromHandle = await _handler.Handle(request);
            return global::MiniBus.Result<global::TestApp.HandlerB.Response>.Success(fromHandle);
        }
    }
}
