//HintName: ExecuteAsyncPipelineHandlerDispatcher_9ef463e0.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class ExecuteAsyncPipelineHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.ExecuteAsyncPipelineHandler.Request,
            global::TestApp.ExecuteAsyncPipelineHandler.Response>
    {
        private readonly global::TestApp.ExecuteAsyncPipelineHandler _handler;

        public ExecuteAsyncPipelineHandlerDispatcher(global::TestApp.ExecuteAsyncPipelineHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.ExecuteAsyncPipelineHandler);

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.ExecuteAsyncPipelineHandler.Response>>
            Handle(global::TestApp.ExecuteAsyncPipelineHandler.Request request)
        {
            var fromLoad = _handler.Load(request);

            var fromValidate = _handler.Validate(fromLoad);
            if (!fromValidate.IsValid())
                return global::MiniBus.Result<global::TestApp.ExecuteAsyncPipelineHandler.Response>.Invalid(fromValidate);

            var fromExecuteAsync = await _handler.ExecuteAsync(fromLoad);
            return global::MiniBus.Result<global::TestApp.ExecuteAsyncPipelineHandler.Response>.Success(fromExecuteAsync);
        }
    }
}
