//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddMiniBus(
            this IServiceCollection services)
        {
            services.AddMiniBusCore();
            services.AddGeneratedHandlers();
            return services;
        }

        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::MiniBus.MiniBus>();
            services.AddScoped<global::TestApp.FullPipelineHandler>();
            services.AddScoped<
                global::MiniBus.IDispatcher<
                    global::TestApp.FullPipelineHandler.Request,
                    global::TestApp.FullPipelineHandler.Response>,
                global::TestApp.FullPipelineHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>>
            Handle(this global::MiniBus.MiniBus bus, global::TestApp.FullPipelineHandler.Request request)
            => bus.Handle<global::TestApp.FullPipelineHandler.Request, global::TestApp.FullPipelineHandler.Response>(request);
    }
}
