//HintName: HandlerADispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class HandlerADispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.HandlerA.Request,
            global::TestApp.HandlerA.Response>
    {
        private readonly global::TestApp.HandlerA _handler;

        public HandlerADispatcher(global::TestApp.HandlerA handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.HandlerA.Response>>
            Handle(global::TestApp.HandlerA.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Result<global::TestApp.HandlerA.Response>.Success(response);
        }
    }
}
