//HintName: FullPipelineHandlerDispatcher_c3df660e.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class FullPipelineHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.FullPipelineHandler.Request,
            global::TestApp.FullPipelineHandler.Response>
    {
        private readonly global::TestApp.FullPipelineHandler _handler;

        public FullPipelineHandlerDispatcher(global::TestApp.FullPipelineHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.FullPipelineHandler);

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>>
            Handle(global::TestApp.FullPipelineHandler.Request request)
        {
            var loaded = await _handler.Load(request);
            if (loaded is not { } loadedValue)
                return global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>.NotFound();

            var validationResult = _handler.Validate(loadedValue);
            if (!validationResult.IsValid())
                return global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>.Invalid(validationResult);

            var response = await _handler.Handle(loadedValue);
            return global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>.Success(response);
        }
    }
}
