//HintName: MixedConventionHandlerDispatcher_4bd88982.g.cs
// <auto-generated/>
#nullable enable
using Microsoft.Extensions.DependencyInjection;

namespace TestApp
{
    public class MixedConventionHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.MixedConventionHandler.Request,
            global::TestApp.MixedConventionHandler.Response>
    {
        private readonly global::TestApp.MixedConventionHandler _handler;
        private readonly global::System.IServiceProvider _serviceProvider;

        public MixedConventionHandlerDispatcher(global::TestApp.MixedConventionHandler handler, global::System.IServiceProvider serviceProvider)
        {
            _handler = handler;
            _serviceProvider = serviceProvider;
        }

        public string HandlerName => nameof(global::TestApp.MixedConventionHandler);

        public global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.MixedConventionHandler.Response>>
            Handle(global::TestApp.MixedConventionHandler.Request request)
        {
            var fromValidate = global::TestApp.MixedConventionHandler.Validate(request, _serviceProvider.GetRequiredService<global::TestApp.IClock>());
            if (!fromValidate.IsValid())
                return global::System.Threading.Tasks.Task.FromResult(global::MiniBus.Result<global::TestApp.MixedConventionHandler.Response>.Invalid(fromValidate));

            var fromHandle = _handler.Handle(request);
            return global::System.Threading.Tasks.Task.FromResult(global::MiniBus.Result<global::TestApp.MixedConventionHandler.Response>.Success(fromHandle));
        }
    }
}
