//HintName: StaticConventionHandlerDispatcher_f6924454.g.cs
// <auto-generated/>
#nullable enable
using Microsoft.Extensions.DependencyInjection;

namespace TestApp
{
    public class StaticConventionHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.StaticConventionHandler.Request,
            global::TestApp.StaticConventionHandler.Response>
    {
        private readonly global::System.IServiceProvider _serviceProvider;

        public StaticConventionHandlerDispatcher(global::System.IServiceProvider serviceProvider)
        {
            _serviceProvider = serviceProvider;
        }

        public string HandlerName => nameof(global::TestApp.StaticConventionHandler);

        public global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.StaticConventionHandler.Response>>
            Handle(global::TestApp.StaticConventionHandler.Request request)
        {
            var fromValidate = global::TestApp.StaticConventionHandler.Validate(request, _serviceProvider.GetService<global::TestApp.IClock>());
            if (!fromValidate.IsValid())
                return global::System.Threading.Tasks.Task.FromResult(global::MiniBus.Result<global::TestApp.StaticConventionHandler.Response>.Invalid(fromValidate));

            var response = global::TestApp.StaticConventionHandler.Handle(request, _serviceProvider.GetRequiredService<global::TestApp.IClock>());
            return global::System.Threading.Tasks.Task.FromResult(global::MiniBus.Result<global::TestApp.StaticConventionHandler.Response>.Success(response));
        }
    }
}
