//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.NonNullableValueTypeHandler>();
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.NonNullableValueTypeHandler.Request,
                    global::TestApp.NonNullableValueTypeHandlerDispatcher.Result>,
                global::TestApp.NonNullableValueTypeHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::TestApp.NonNullableValueTypeHandlerDispatcher.Result>
            Handle(this global::MiniBus.MiniBus bus, global::TestApp.NonNullableValueTypeHandler.Request request)
            => bus.Handle<global::TestApp.NonNullableValueTypeHandler.Request, global::TestApp.NonNullableValueTypeHandlerDispatcher.Result>(request);
    }
}
