//HintName: FullPipelineHandlerDispatcher_c3df660e.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class FullPipelineHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.FullPipelineHandler.Request,
            global::TestApp.FullPipelineHandler.Response>
    {
        private readonly global::TestApp.FullPipelineHandler _handler;

        public FullPipelineHandlerDispatcher(global::TestApp.FullPipelineHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.FullPipelineHandler);

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>>
            Handle(global::TestApp.FullPipelineHandler.Request request)
        {
            var fromLoad = await _handler.Load(request);
            if (fromLoad is not { } fromLoadValue)
                return global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>.NotFound("entity cannot be null");

            var fromValidate = _handler.Validate(fromLoadValue);
            if (!fromValidate.IsValid())
                return global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>.Invalid(fromValidate);

            var fromHandle = await _handler.Handle(fromLoadValue);
            return global::MiniBus.Result<global::TestApp.FullPipelineHandler.Response>.Success(fromHandle);
        }
    }
}
