//HintName: HandlerTwoDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class HandlerTwoDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.SharedRequest,
            global::TestApp.HandlerTwo.Response>
    {
        private readonly global::TestApp.HandlerTwo _handler;

        public HandlerTwoDispatcher(global::TestApp.HandlerTwo handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.HandlerTwo.Response>>
            Handle(global::TestApp.SharedRequest request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Result<global::TestApp.HandlerTwo.Response>.Success(response);
        }
    }
}
