//HintName: NullableHandleReturnHandlerDispatcher_c3bc60ec.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class NullableHandleReturnHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.NullableHandleReturnHandler.Request,
            global::TestApp.NullableHandleReturnHandler.Response>
    {
        private readonly global::TestApp.NullableHandleReturnHandler _handler;

        public NullableHandleReturnHandlerDispatcher(global::TestApp.NullableHandleReturnHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.NullableHandleReturnHandler);

        public global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.NullableHandleReturnHandler.Response>>
            Handle(global::TestApp.NullableHandleReturnHandler.Request request)
        {
            var fromHandle = _handler.Handle(request);
            if (fromHandle is not { } fromHandleValue)
                return global::System.Threading.Tasks.Task.FromResult(global::MiniBus.Result<global::TestApp.NullableHandleReturnHandler.Response>.NotFound("response cannot be null"));
            var fromAfterAudit = _handler.AfterAudit(fromHandleValue);

            return global::System.Threading.Tasks.Task.FromResult(global::MiniBus.Result<global::TestApp.NullableHandleReturnHandler.Response>.Success(fromHandleValue));
        }
    }
}
