//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddMiniBus(
            this IServiceCollection services)
        {
            services.AddMiniBusCore();
            services.AddGeneratedHandlers();
            return services;
        }

        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::MiniBus.MiniBus>();
            services.AddScoped<global::TestApp.HandlerOne>();
            services.AddScoped<
                global::MiniBus.IDispatcher<
                    global::TestApp.SharedRequest,
                    global::TestApp.HandlerOne.Response>,
                global::TestApp.HandlerOneDispatcher>();
            services.AddScoped<global::TestApp.HandlerTwo>();
            services.AddScoped<
                global::MiniBus.IDispatcher<
                    global::TestApp.SharedRequest,
                    global::TestApp.HandlerTwo.Response>,
                global::TestApp.HandlerTwoDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
    }
}
