//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.HandlerA>();
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.HandlerA.Request,
                    global::TestApp.HandlerADispatcher.Result>,
                global::TestApp.HandlerADispatcher>();
            services.AddTransient<global::TestApp.HandlerB>();
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.HandlerB.Request,
                    global::TestApp.HandlerBDispatcher.Result>,
                global::TestApp.HandlerBDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::TestApp.HandlerADispatcher.Result>
            Handle(this global::MiniBus.MiniBus bus, global::TestApp.HandlerA.Request request)
            => bus.Handle<global::TestApp.HandlerA.Request, global::TestApp.HandlerADispatcher.Result>(request);
        public static global::System.Threading.Tasks.Task<global::TestApp.HandlerBDispatcher.Result>
            Handle(this global::MiniBus.MiniBus bus, global::TestApp.HandlerB.Request request)
            => bus.Handle<global::TestApp.HandlerB.Request, global::TestApp.HandlerBDispatcher.Result>(request);
    }
}
