//HintName: NonNullableValueTypeHandlerDispatcher_8a11e9e5.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class NonNullableValueTypeHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.NonNullableValueTypeHandler.Request,
            NonNullableValueTypeHandlerDispatcher.Result>
    {
        public sealed class Result : global::MiniBus.IDispatchResult
        {
            private Result() { }

            public Result(int value)
            {
                Value = value;
            }

            public object? Value { get; }

            public T Match<T>(
                global::System.Func<int, T> onSuccess
            )
            {
                return Value switch
                {
                    int value => onSuccess(value),
                    _ => throw new global::System.InvalidOperationException("Unknown result value type.")
                };
            }
        }
        private readonly global::TestApp.NonNullableValueTypeHandler _handler;

        public NonNullableValueTypeHandlerDispatcher(global::TestApp.NonNullableValueTypeHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.NonNullableValueTypeHandler);

        public global::System.Threading.Tasks.Task<Result>
            Handle(global::TestApp.NonNullableValueTypeHandler.Request request)
        {
            var fromHandle = _handler.Handle(request);
            return global::System.Threading.Tasks.Task.FromResult(new Result(fromHandle));
        }
    }
}
