//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.HandlerOne>();
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.SharedRequest,
                    global::TestApp.HandlerOneDispatcher.Result>,
                global::TestApp.HandlerOneDispatcher>();
            services.AddTransient<global::TestApp.HandlerTwo>();
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.SharedRequest,
                    global::TestApp.HandlerTwoDispatcher.Result>,
                global::TestApp.HandlerTwoDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
    }
}
