//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.FullPipelineWithFinallyHandler>();
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.FullPipelineWithFinallyHandler.Request,
                    global::TestApp.FullPipelineWithFinallyHandlerDispatcher.Result>,
                global::TestApp.FullPipelineWithFinallyHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::TestApp.FullPipelineWithFinallyHandlerDispatcher.Result>
            Handle(this global::MiniBus.MiniBus bus, global::TestApp.FullPipelineWithFinallyHandler.Request request)
            => bus.Handle<global::TestApp.FullPipelineWithFinallyHandler.Request, global::TestApp.FullPipelineWithFinallyHandlerDispatcher.Result>(request);
    }
}
