//HintName: FullPipelineHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class FullPipelineHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.FullPipelineHandler.Request,
            global::TestApp.FullPipelineHandler.Response>
    {
        private readonly global::TestApp.FullPipelineHandler _handler;

        public FullPipelineHandlerDispatcher(global::TestApp.FullPipelineHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.FullPipelineHandler.Response>>
            Handle(global::TestApp.FullPipelineHandler.Request request)
        {
            var loaded = await _handler.Load(request);
            if (loaded is null)
                return global::MiniBus.Convention.Result<global::TestApp.FullPipelineHandler.Response>.NotFound();

            var validationResult = _handler.Validate(loaded);
            if (!validationResult.IsValid())
                return global::MiniBus.Convention.Result<global::TestApp.FullPipelineHandler.Response>.Invalid(validationResult);

            var response = await _handler.Handle(loaded);
            return global::MiniBus.Convention.Result<global::TestApp.FullPipelineHandler.Response>.Success(response);
        }
    }
}
