//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.BeforeConventionPipelineHandler>();
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.BeforeConventionPipelineHandler.Request,
                    global::TestApp.BeforeConventionPipelineHandler.Response>,
                global::TestApp.BeforeConventionPipelineHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::MiniBus.Result<global::TestApp.BeforeConventionPipelineHandler.Response>>
            Handle(this global::MiniBus.MiniBus bus, global::TestApp.BeforeConventionPipelineHandler.Request request)
            => bus.Handle<global::TestApp.BeforeConventionPipelineHandler.Request, global::TestApp.BeforeConventionPipelineHandler.Response>(request);
    }
}
