//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<
                global::MiniBus.IDispatcher<
                    global::TestApp.StaticConventionHandler.Request,
                    global::TestApp.StaticConventionHandler.Response>,
                global::TestApp.StaticConventionHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::MiniBus.Result<global::TestApp.StaticConventionHandler.Response>>
            Handle(this global::MiniBus.MiniBus bus, global::TestApp.StaticConventionHandler.Request request)
            => bus.Handle<global::TestApp.StaticConventionHandler.Request, global::TestApp.StaticConventionHandler.Response>(request);
    }
}
