//HintName: MiniBusRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddMiniBus(
            this IServiceCollection services)
        {
            services.AddMiniBusCore();
            services.AddGeneratedHandlers();
            return services;
        }

        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::MiniBus.MiniBus>();
            return services;
        }
    }

    // ── Typed MiniBus extension methods ──────────────────────────────
    public static class MiniBusExtensions
    {
    }
}
