//HintName: FullPipelineWithFinallyHandlerDispatcher_18a90eb0.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class FullPipelineWithFinallyHandlerDispatcher
        : global::MiniBus.IDispatcher<
            global::TestApp.FullPipelineWithFinallyHandler.Request,
            global::TestApp.FullPipelineWithFinallyHandler.Response>
    {
        private readonly global::TestApp.FullPipelineWithFinallyHandler _handler;

        public FullPipelineWithFinallyHandlerDispatcher(global::TestApp.FullPipelineWithFinallyHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.FullPipelineWithFinallyHandler);

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Result<global::TestApp.FullPipelineWithFinallyHandler.Response>>
            Handle(global::TestApp.FullPipelineWithFinallyHandler.Request request)
        {
            global::TestApp.FullPipelineWithFinallyHandler.Entity? fromLoad = null;

            try
            {
                fromLoad = await _handler.Load(request);
                if (fromLoad is not { } fromLoadValue)
                    return global::MiniBus.Result<global::TestApp.FullPipelineWithFinallyHandler.Response>.NotFound("entity cannot be null");

                var fromValidate = _handler.Validate(fromLoadValue);
                if (!fromValidate.IsValid())
                    return global::MiniBus.Result<global::TestApp.FullPipelineWithFinallyHandler.Response>.Invalid(fromValidate);

                var fromHandle = await _handler.Handle(fromLoadValue);
                return global::MiniBus.Result<global::TestApp.FullPipelineWithFinallyHandler.Response>.Success(fromHandle);
            }
            finally
            {
                await _handler.FinallyAsync(request, fromLoad);
            }
        }
    }
}
