//HintName: ReversedParamsHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class ReversedParamsHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.ReversedParamsHandler.Request,
            global::TestApp.ReversedParamsHandler.Response>
    {
        private readonly global::TestApp.ReversedParamsHandler _handler;

        public ReversedParamsHandlerDispatcher(global::TestApp.ReversedParamsHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.ReversedParamsHandler.Response>>
            Handle(global::TestApp.ReversedParamsHandler.Request request)
        {
            var loaded = await _handler.Load(request);
            if (loaded is null)
                return global::MiniBus.Convention.Result<global::TestApp.ReversedParamsHandler.Response>.NotFound();

            var response = await _handler.Handle(loaded, request);
            return global::MiniBus.Convention.Result<global::TestApp.ReversedParamsHandler.Response>.Success(response);
        }
    }
}
