//HintName: SyncLoadHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class SyncLoadHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.SyncLoadHandler.Request,
            global::TestApp.SyncLoadHandler.Response>
    {
        private readonly global::TestApp.SyncLoadHandler _handler;

        public SyncLoadHandlerDispatcher(global::TestApp.SyncLoadHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.SyncLoadHandler.Response>>
            Handle(global::TestApp.SyncLoadHandler.Request request)
        {
            var loaded = _handler.Load(request);
            if (loaded is null)
                return global::MiniBus.Convention.Result<global::TestApp.SyncLoadHandler.Response>.NotFound();

            var response = await _handler.Handle(loaded);
            return global::MiniBus.Convention.Result<global::TestApp.SyncLoadHandler.Response>.Success(response);
        }
    }
}
