//HintName: NonNullableLoadHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class NonNullableLoadHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.NonNullableLoadHandler.Request,
            global::TestApp.NonNullableLoadHandler.Response>
    {
        private readonly global::TestApp.NonNullableLoadHandler _handler;

        public NonNullableLoadHandlerDispatcher(global::TestApp.NonNullableLoadHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.NonNullableLoadHandler.Response>>
            Handle(global::TestApp.NonNullableLoadHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.NonNullableLoadHandler.Response>.Success(response);
        }
    }
}
