//HintName: NoLoadHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class NoLoadHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.NoLoadHandler.Request,
            global::TestApp.NoLoadHandler.Response>
    {
        private readonly global::TestApp.NoLoadHandler _handler;

        public NoLoadHandlerDispatcher(global::TestApp.NoLoadHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.NoLoadHandler.Response>>
            Handle(global::TestApp.NoLoadHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.NoLoadHandler.Response>.Success(response);
        }
    }
}
