//HintName: ConventionRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace MiniBus.Convention
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddScoped<global::TestApp.NonNullableLoadHandler>();
            services.AddScoped<
                global::MiniBus.Convention.IConventionHandler<
                    global::TestApp.NonNullableLoadHandler.Request,
                    global::TestApp.NonNullableLoadHandler.Response>,
                global::TestApp.NonNullableLoadHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed ConventionBus extension methods ──────────────────────────────
    public static class ConventionBusExtensions
    {
        public static global::System.Threading.Tasks.Task<global::MiniBus.Convention.Result<global::TestApp.NonNullableLoadHandler.Response>>
            Handle(this global::MiniBus.Convention.ConventionBus bus, global::TestApp.NonNullableLoadHandler.Request request)
            => bus.Handle<global::TestApp.NonNullableLoadHandler.Request, global::TestApp.NonNullableLoadHandler.Response>(request);
    }
}
