//HintName: BothParamsHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class BothParamsHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.BothParamsHandler.Request,
            global::TestApp.BothParamsHandler.Response>
    {
        private readonly global::TestApp.BothParamsHandler _handler;

        public BothParamsHandlerDispatcher(global::TestApp.BothParamsHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.BothParamsHandler.Response>>
            Handle(global::TestApp.BothParamsHandler.Request request)
        {
            var loaded = await _handler.Load(request);
            if (loaded is null)
                return global::MiniBus.Convention.Result<global::TestApp.BothParamsHandler.Response>.NotFound();

            var response = await _handler.Handle(request, loaded);
            return global::MiniBus.Convention.Result<global::TestApp.BothParamsHandler.Response>.Success(response);
        }
    }
}
