//HintName: EntityHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class EntityHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.EntityHandler.Request,
            global::TestApp.EntityHandler.Response>
    {
        private readonly global::TestApp.EntityHandler _handler;

        public EntityHandlerDispatcher(global::TestApp.EntityHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.EntityHandler.Response>>
            Handle(global::TestApp.EntityHandler.Request request)
        {
            var loaded = await _handler.Load(request);
            if (loaded is null)
                return global::MiniBus.Convention.Result<global::TestApp.EntityHandler.Response>.NotFound();

            var response = await _handler.Handle(loaded);
            return global::MiniBus.Convention.Result<global::TestApp.EntityHandler.Response>.Success(response);
        }
    }
}
