//HintName: AllNullableHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class AllNullableHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.AllNullableHandler.Request,
            global::TestApp.AllNullableHandler.Response>
    {
        private readonly global::TestApp.AllNullableHandler _handler;

        public AllNullableHandlerDispatcher(global::TestApp.AllNullableHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.AllNullableHandler.Response>>
            Handle(global::TestApp.AllNullableHandler.Request request)
        {
            var (a, b) = await _handler.Load(request);
            if (a is null || b is null)
                return global::MiniBus.Convention.Result<global::TestApp.AllNullableHandler.Response>.NotFound();

            var response = await _handler.Handle(a, b);
            return global::MiniBus.Convention.Result<global::TestApp.AllNullableHandler.Response>.Success(response);
        }
    }
}
