//HintName: AsyncTupleHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class AsyncTupleHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.AsyncTupleHandler.Request,
            global::TestApp.AsyncTupleHandler.Response>
    {
        private readonly global::TestApp.AsyncTupleHandler _handler;

        public AsyncTupleHandlerDispatcher(global::TestApp.AsyncTupleHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.AsyncTupleHandler.Response>>
            Handle(global::TestApp.AsyncTupleHandler.Request request)
        {
            var (entity, config) = await _handler.Load(request);
            if (entity is null || config is null)
                return global::MiniBus.Convention.Result<global::TestApp.AsyncTupleHandler.Response>.NotFound();

            var response = await _handler.Handle(entity, config);
            return global::MiniBus.Convention.Result<global::TestApp.AsyncTupleHandler.Response>.Success(response);
        }
    }
}
