//HintName: PartialNullableHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class PartialNullableHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.PartialNullableHandler.Request,
            global::TestApp.PartialNullableHandler.Response>
    {
        private readonly global::TestApp.PartialNullableHandler _handler;

        public PartialNullableHandlerDispatcher(global::TestApp.PartialNullableHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.PartialNullableHandler.Response>>
            Handle(global::TestApp.PartialNullableHandler.Request request)
        {
            var (a, b) = await _handler.Load(request);
            if (a is null)
                return global::MiniBus.Convention.Result<global::TestApp.PartialNullableHandler.Response>.NotFound();

            var response = await _handler.Handle(a, b);
            return global::MiniBus.Convention.Result<global::TestApp.PartialNullableHandler.Response>.Success(response);
        }
    }
}
