//HintName: NamedTupleHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class NamedTupleHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.NamedTupleHandler.Request,
            global::TestApp.NamedTupleHandler.Response>
    {
        private readonly global::TestApp.NamedTupleHandler _handler;

        public NamedTupleHandlerDispatcher(global::TestApp.NamedTupleHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.NamedTupleHandler.Response>>
            Handle(global::TestApp.NamedTupleHandler.Request request)
        {
            var (entity, config) = await _handler.Load(request);
            if (entity is null || config is null)
                return global::MiniBus.Convention.Result<global::TestApp.NamedTupleHandler.Response>.NotFound();

            var response = await _handler.Handle(entity, config);
            return global::MiniBus.Convention.Result<global::TestApp.NamedTupleHandler.Response>.Success(response);
        }
    }
}
