//HintName: UnnamedTupleHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class UnnamedTupleHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.UnnamedTupleHandler.Request,
            global::TestApp.UnnamedTupleHandler.Response>
    {
        private readonly global::TestApp.UnnamedTupleHandler _handler;

        public UnnamedTupleHandlerDispatcher(global::TestApp.UnnamedTupleHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.UnnamedTupleHandler.Response>>
            Handle(global::TestApp.UnnamedTupleHandler.Request request)
        {
            var (item1, item2) = await _handler.Load(request);
            if (item1 is null || item2 is null)
                return global::MiniBus.Convention.Result<global::TestApp.UnnamedTupleHandler.Response>.NotFound();

            var response = await _handler.Handle(item1, item2);
            return global::MiniBus.Convention.Result<global::TestApp.UnnamedTupleHandler.Response>.Success(response);
        }
    }
}
