//HintName: NonNullableTupleHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class NonNullableTupleHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.NonNullableTupleHandler.Request,
            global::TestApp.NonNullableTupleHandler.Response>
    {
        private readonly global::TestApp.NonNullableTupleHandler _handler;

        public NonNullableTupleHandlerDispatcher(global::TestApp.NonNullableTupleHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.NonNullableTupleHandler.Response>>
            Handle(global::TestApp.NonNullableTupleHandler.Request request)
        {
            var (a, b) = await _handler.Load(request);

            var response = await _handler.Handle(a, b);
            return global::MiniBus.Convention.Result<global::TestApp.NonNullableTupleHandler.Response>.Success(response);
        }
    }
}
