//HintName: BothParamValidateHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class BothParamValidateHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.BothParamValidateHandler.Request,
            global::TestApp.BothParamValidateHandler.Response>
    {
        private readonly global::TestApp.BothParamValidateHandler _handler;

        public BothParamValidateHandlerDispatcher(global::TestApp.BothParamValidateHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.BothParamValidateHandler.Response>>
            Handle(global::TestApp.BothParamValidateHandler.Request request)
        {
            var loaded = await _handler.Load(request);
            if (loaded is null)
                return global::MiniBus.Convention.Result<global::TestApp.BothParamValidateHandler.Response>.NotFound();

            var validationResult = _handler.Validate(request, loaded);
            if (!validationResult.IsValid())
                return global::MiniBus.Convention.Result<global::TestApp.BothParamValidateHandler.Response>.Invalid(validationResult);

            var response = await _handler.Handle(loaded);
            return global::MiniBus.Convention.Result<global::TestApp.BothParamValidateHandler.Response>.Success(response);
        }
    }
}
