//HintName: LoadedValidateHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class LoadedValidateHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.LoadedValidateHandler.Request,
            global::TestApp.LoadedValidateHandler.Response>
    {
        private readonly global::TestApp.LoadedValidateHandler _handler;

        public LoadedValidateHandlerDispatcher(global::TestApp.LoadedValidateHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.LoadedValidateHandler.Response>>
            Handle(global::TestApp.LoadedValidateHandler.Request request)
        {
            var loaded = await _handler.Load(request);
            if (loaded is null)
                return global::MiniBus.Convention.Result<global::TestApp.LoadedValidateHandler.Response>.NotFound();

            var validationResult = _handler.Validate(loaded);
            if (!validationResult.IsValid())
                return global::MiniBus.Convention.Result<global::TestApp.LoadedValidateHandler.Response>.Invalid(validationResult);

            var response = await _handler.Handle(loaded);
            return global::MiniBus.Convention.Result<global::TestApp.LoadedValidateHandler.Response>.Success(response);
        }
    }
}
