//HintName: SyncValidateHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class SyncValidateHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.SyncValidateHandler.Request,
            global::TestApp.SyncValidateHandler.Response>
    {
        private readonly global::TestApp.SyncValidateHandler _handler;

        public SyncValidateHandlerDispatcher(global::TestApp.SyncValidateHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.SyncValidateHandler.Response>>
            Handle(global::TestApp.SyncValidateHandler.Request request)
        {
            var validationResult = _handler.Validate(request);
            if (!validationResult.IsValid())
                return global::MiniBus.Convention.Result<global::TestApp.SyncValidateHandler.Response>.Invalid(validationResult);

            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.SyncValidateHandler.Response>.Success(response);
        }
    }
}
