//HintName: AsyncValidateHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class AsyncValidateHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.AsyncValidateHandler.Request,
            global::TestApp.AsyncValidateHandler.Response>
    {
        private readonly global::TestApp.AsyncValidateHandler _handler;

        public AsyncValidateHandlerDispatcher(global::TestApp.AsyncValidateHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.AsyncValidateHandler.Response>>
            Handle(global::TestApp.AsyncValidateHandler.Request request)
        {
            var validationResult = await _handler.Validate(request);
            if (!validationResult.IsValid())
                return global::MiniBus.Convention.Result<global::TestApp.AsyncValidateHandler.Response>.Invalid(validationResult);

            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.AsyncValidateHandler.Response>.Success(response);
        }
    }
}
