//HintName: WrongValidateHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class WrongValidateHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.WrongValidateHandler.Request,
            global::TestApp.WrongValidateHandler.Response>
    {
        private readonly global::TestApp.WrongValidateHandler _handler;

        public WrongValidateHandlerDispatcher(global::TestApp.WrongValidateHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.WrongValidateHandler.Response>>
            Handle(global::TestApp.WrongValidateHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.WrongValidateHandler.Response>.Success(response);
        }
    }
}
