//HintName: NoValidateHandlerDispatcher.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public class NoValidateHandlerDispatcher
        : global::MiniBus.Convention.IConventionHandler<
            global::TestApp.NoValidateHandler.Request,
            global::TestApp.NoValidateHandler.Response>
    {
        private readonly global::TestApp.NoValidateHandler _handler;

        public NoValidateHandlerDispatcher(global::TestApp.NoValidateHandler handler)
        {
            _handler = handler;
        }

        public async global::System.Threading.Tasks.Task<
            global::MiniBus.Convention.Result<global::TestApp.NoValidateHandler.Response>>
            Handle(global::TestApp.NoValidateHandler.Request request)
        {
            var response = await _handler.Handle(request);
            return global::MiniBus.Convention.Result<global::TestApp.NoValidateHandler.Response>.Success(response);
        }
    }
}
