using Microsoft.Extensions.DependencyInjection;

namespace MiniBus;

public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Registers the core <see cref="MiniBus"/> service.
    /// You must also call <c>AddGeneratedHandlers()</c> (generated by MiniBus.Generator)
    /// to register your handler dispatchers and typed extension methods.
    /// </summary>
    public static IServiceCollection AddMiniBusCore(this IServiceCollection services)
    {
        services.AddTransient<MiniBus>();
        return services;
    }
}
