using Caravelle.Generator.Handler;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;

namespace Caravelle.Generator.SourceBuilders;

public static class DispatcherSourceBuilder
{
    public static string Build(HandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.HasFromServicesParameters)
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // ── Dispatcher class ─────────────────────────────────────────────────
        var inNs = model.Namespace is not null;
        var i = inNs ? "    " : "";     // indent when inside a namespace block
        var asyncKeyword = model.IsAnyAsync ? "async " : "";
        var taskWrap = model.IsAnyAsync ? "" : "global::System.Threading.Tasks.Task.FromResult(";
        var taskClose = model.IsAnyAsync ? "" : ")";

        if (inNs) { sb.AppendLine($"namespace {model.Namespace}"); sb.AppendLine("{"); }

        sb.AppendLine($"{i}public sealed class {model.ClassName}Dispatcher");
        sb.AppendLine($"{i}    : global::Caravelle.IDispatcher<");
        sb.AppendLine($"{i}        {model.FullRequestType},");
        var implementsResultType = model.HasSingleResultType ? model.ResultTypeName : model.ClassName + "Dispatcher.Result";
        sb.AppendLine($"{i}        {implementsResultType}>");
        sb.AppendLine($"{i}{{");

        if (!model.HasSingleResultType)
            ResultTypeSourceBuilder.Build(sb, model, i);

        // Only non-static middleware-owned phases need a DI-resolved instance field —
        // static middleware methods are called directly via the middleware's type name,
        // same as static handler methods. Ordered by type name for deterministic output.
        var middlewareFieldNames = model.Phases
            .Concat(model.FinallyPhases)
            .Where(static p => p.OwnerTypeFullName is not null && !p.IsStatic)
            .Select(static p => p.OwnerTypeFullName!)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static t => t, StringComparer.Ordinal)
            .ToDictionary(static t => t, GetMiddlewareFieldName, StringComparer.Ordinal);

        if (model.HasInstanceMethods)
            sb.AppendLine($"{i}    private readonly {model.FullClassName} _handler;");
        foreach (var middlewareField in middlewareFieldNames)
            sb.AppendLine($"{i}    private readonly {middlewareField.Key} {middlewareField.Value};");
        if (model.HasFromServicesParameters)
            sb.AppendLine($"{i}    private readonly global::System.IServiceProvider _serviceProvider;");

        if (model.HasInstanceMethods || middlewareFieldNames.Count > 0 || model.HasFromServicesParameters)
        {
            sb.AppendLine();

            var ctorParameters = new List<string>();
            if (model.HasInstanceMethods)
                ctorParameters.Add($"{model.FullClassName} handler");
            foreach (var middlewareField in middlewareFieldNames)
                ctorParameters.Add($"{middlewareField.Key} {middlewareField.Value.TrimStart('_')}");
            if (model.HasFromServicesParameters)
                ctorParameters.Add("global::System.IServiceProvider serviceProvider");

            sb.AppendLine($"{i}    public {model.ClassName}Dispatcher({string.Join(", ", ctorParameters)})");
            sb.AppendLine($"{i}    {{");
            if (model.HasInstanceMethods)
                sb.AppendLine($"{i}        _handler = handler;");
            foreach (var middlewareField in middlewareFieldNames)
                sb.AppendLine($"{i}        {middlewareField.Value} = {middlewareField.Value.TrimStart('_')};");
            if (model.HasFromServicesParameters)
                sb.AppendLine($"{i}        _serviceProvider = serviceProvider;");
            sb.AppendLine($"{i}    }}");
        }

        sb.AppendLine();
        sb.AppendLine($"{i}    public string HandlerName => nameof({model.FullClassName});");
        sb.AppendLine();
        var handleReturnType = model.HasSingleResultType ? model.ResultTypeName : "Result";
        sb.AppendLine($"{i}    public {asyncKeyword}global::System.Threading.Tasks.Task<{handleReturnType}>");
        sb.AppendLine($"{i}        Handle({model.FullRequestType} request)");
        sb.AppendLine($"{i}    {{");

        var finallyPhases = model.FinallyPhases;

        // Hoist variables needed by Finally before try block
        var hoistedTypes = new HashSet<string>(StringComparer.Ordinal);
        var hoistedLocalNames = new Dictionary<string, string>(StringComparer.Ordinal);
        if (finallyPhases.Count > 0)
        {
            var returnLocalsByType = model.Phases
                .SelectMany(phase => phase.Returns)
                .GroupBy(element => element.FullType)
                .ToDictionary(group => group.Key, group => group.First().LocalName, StringComparer.Ordinal);

            foreach (var finallyPhase in finallyPhases)
            {
                foreach (var param in finallyPhase.Parameters)
                {
                    if (!param.IsFromServices
                        && returnLocalsByType.TryGetValue(param.FullType, out var nullableLocalName)
                        && hoistedTypes.Add(param.FullType))
                    {
                        hoistedLocalNames[param.FullType] = nullableLocalName;
                        sb.AppendLine($"{i}        {param.FullType}? {nullableLocalName} = null;");
                    }
                }
            }
            if (hoistedTypes.Count > 0)
                sb.AppendLine();
        }

        // Start try block if Finally exists
        if (finallyPhases.Count > 0)
        {
            sb.AppendLine($"{i}        try");
            sb.AppendLine($"{i}        {{");
        }

        string? responseLocalName = null;
        var phaseIndent = finallyPhases.Count > 0 ? i + "    " : i;

        foreach (var phase in model.Phases)
        {
            switch (phase.Type)
            {
                case PhaseType.Before:
                    BuildPipelinePhase(sb, model, phase, taskWrap, taskClose, phaseIndent, hoistedTypes, middlewareFieldNames);
                    break;
                case PhaseType.Handle:
                    responseLocalName = BuildHandlePhase(sb, model, phase, taskWrap, taskClose, phaseIndent, hoistedTypes);
                    break;
                case PhaseType.After:
                    BuildPipelinePhase(sb, model, phase, taskWrap, taskClose, phaseIndent, hoistedTypes, middlewareFieldNames);
                    break;
            }
        }

        var returnIndent = finallyPhases.Count > 0 ? i + "            " : i + "        ";
        if (model.HasSingleResultType)
            sb.AppendLine($"{returnIndent}return {taskWrap}{responseLocalName ?? "default!"}{taskClose};");
        else
            sb.AppendLine($"{returnIndent}return {taskWrap}new Result({responseLocalName ?? "default!"}){taskClose};");

        // Close try and add finally
        if (finallyPhases.Count > 0)
        {
            sb.AppendLine($"{i}        }}");
            sb.AppendLine($"{i}        finally");
            sb.AppendLine($"{i}        {{");
            foreach (var finallyPhase in finallyPhases)
            {
                BuildFinallyPhase(sb, model, finallyPhase, i, hoistedLocalNames, middlewareFieldNames);
            }
            sb.AppendLine($"{i}        }}");
        }

        sb.AppendLine($"{i}    }}");
        sb.AppendLine($"{i}}}");
        if (inNs) sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Resolves the call target for a phase: the middleware's type name for a static
    /// middleware method, a dedicated DI-resolved field for an instance middleware method,
    /// the handler's own type name for a static handler method, or <c>_handler</c> for an
    /// own-class/inherited instance method (unchanged from before middleware support).
    /// </summary>
    private static string GetMethodTarget(HandlerModel model, MethodPhase phase, IReadOnlyDictionary<string, string> middlewareFieldNames)
    {
        if (phase.OwnerTypeFullName is { } ownerType)
            return phase.IsStatic ? ownerType : middlewareFieldNames[ownerType];

        return phase.IsStatic ? model.FullClassName : "_handler";
    }

    private static string GetMiddlewareFieldName(string fullTypeName)
    {
        using var sha = SHA256.Create();
        var hashBytes = sha.ComputeHash(Encoding.UTF8.GetBytes(fullTypeName));
        var chars = new char[8];
        for (var i = 0; i < 4; i++)
        {
            var b = hashBytes[i];
            chars[i * 2] = ToHexChar((b >> 4) & 0xF);
            chars[i * 2 + 1] = ToHexChar(b & 0xF);
        }

        return $"_{GetShortTypeName(fullTypeName)}_{new string(chars)}";
    }

    /// <summary>
    /// Extracts a camelCase field-friendly name from a fully-qualified type name (e.g.
    /// <c>global::MyApp.Middleware.LoggingMiddleware</c> → <c>loggingMiddleware</c>) for
    /// use as a readable part of the generated field name.
    /// </summary>
    private static string GetShortTypeName(string fullTypeName)
    {
        var name = fullTypeName;

        const string globalPrefix = "global::";
        if (name.StartsWith(globalPrefix, StringComparison.Ordinal))
            name = name.Substring(globalPrefix.Length);

        var lastDot = name.LastIndexOf('.');
        if (lastDot >= 0)
            name = name.Substring(lastDot + 1);

        var genericIndex = name.IndexOf('<');
        if (genericIndex >= 0)
            name = name.Substring(0, genericIndex);

        return name.Length > 0 ? char.ToLowerInvariant(name[0]) + name.Substring(1) : name;
    }

    private static char ToHexChar(int value) =>
        (char)(value < 10 ? '0' + value : 'a' + (value - 10));


    private static void BuildPipelinePhase(StringBuilder sb, HandlerModel model, MethodPhase phase, string taskWrap, string taskClose, string indent, HashSet<string> hoistedTypes, IReadOnlyDictionary<string, string> middlewareFieldNames)
    {
        var awaitPrefix = phase.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(phase, model.LocalVariables));
        var methodTarget = GetMethodTarget(model, phase, middlewareFieldNames);
        if (phase.Returns.Count == 0)
        {
            // void / non-generic Task before/after-handle method: nothing to assign, just
            // invoke it for its side effect.
            sb.AppendLine($"{indent}        {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");
        }
        else if (phase.Returns.Count > 1)
        {
            var hasHoistedReturns = phase.Returns.Any(e => hoistedTypes.Contains(e.FullType));
            if (!hasHoistedReturns)
            {
                var varNames = string.Join(", ", phase.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        var ({varNames}) = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");
            }
            else if (phase.Returns.All(e => hoistedTypes.Contains(e.FullType)))
            {
                var varNames = string.Join(", ", phase.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        ({varNames}) = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");
            }
            else
            {
                var tempNames = phase.Returns
                    .Select((_, index) => $"__{phase.MethodName}Result{index}")
                    .ToArray();
                sb.AppendLine($"{indent}        var ({string.Join(", ", tempNames)}) = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");

                for (var index = 0; index < phase.Returns.Count; index++)
                {
                    var element = phase.Returns[index];
                    var varKeyword = hoistedTypes.Contains(element.FullType) ? "" : "var ";
                    sb.AppendLine($"{indent}        {varKeyword}{element.LocalName} = {tempNames[index]};");
                }
            }
        }
        else
        {
            var isHoisted = hoistedTypes.Contains(phase.Returns[0].FullType);
            var varKeyword = isHoisted ? "" : "var ";
            sb.AppendLine($"{indent}        {varKeyword}{phase.Returns[0].LocalName} = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");
        }

        BuildValidationResultChecks(sb, phase.Returns, taskWrap, taskClose, indent);
        BuildNotFoundChecks(sb, model, phase.Returns, taskWrap, taskClose, indent);

        sb.AppendLine();
    }

    private static void BuildValidationResultChecks(StringBuilder sb, EquatableArray<ReturnElement> returnValues, string taskWrap, string taskClose, string indent)
    {
        foreach (var element in returnValues)
        {
            if (element.IsResultType)
            {
                var validationResultLocalName = $"{element.LocalName}ValidationResult";
                sb.AppendLine($"{indent}        if ({element.LocalName} is global::Caravelle.IValidationResult {validationResultLocalName} && !{validationResultLocalName}.IsValid())");
                sb.AppendLine($"{indent}            return {taskWrap}new Result({element.LocalName}){taskClose};");
            }
        }
    }

    private static void BuildNotFoundChecks(StringBuilder sb, HandlerModel model, EquatableArray<ReturnElement> returnValues, string taskWrap, string taskClose, string indent)
    {
        foreach (var element in returnValues)
        {
            var local = model.LocalVariables.First(l => l.FullType == element.FullType);
            if (local.CheckNullability)
            {
                var ifNullMessage = local.IfNullErrorMessage is null ? "notfound" : $"\"{local.IfNullErrorMessage}\"";
                sb.AppendLine($"{indent}        if ({element.LocalName} is not {{ }} {element.NonNullLocalName})");
                sb.AppendLine($"{indent}            return {taskWrap}new Result(new global::Caravelle.NotFoundResult({ifNullMessage})){taskClose};");
            }
        }
    }

    private static string BuildHandlePhase(StringBuilder sb, HandlerModel model, MethodPhase handle, string taskWrap, string taskClose, string indent, HashSet<string> hoistedTypes)
    {
        var handleAwait = handle.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(handle, model.LocalVariables));
        var methodTarget = handle.IsStatic ? model.FullClassName : "_handler";

        if (handle.Returns.Count > 1)
        {
            var hasHoistedReturns = handle.Returns.Any(e => hoistedTypes.Contains(e.FullType));
            if (!hasHoistedReturns)
            {
                var varNames = string.Join(", ", handle.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        var ({varNames}) = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");
            }
            else if (handle.Returns.All(e => hoistedTypes.Contains(e.FullType)))
            {
                var varNames = string.Join(", ", handle.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        ({varNames}) = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");
            }
            else
            {
                var tempNames = handle.Returns
                    .Select((_, index) => $"__{handle.MethodName}Result{index}")
                    .ToArray();
                sb.AppendLine($"{indent}        var ({string.Join(", ", tempNames)}) = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");

                for (var index = 0; index < handle.Returns.Count; index++)
                {
                    var element = handle.Returns[index];
                    var varKeyword = hoistedTypes.Contains(element.FullType) ? "" : "var ";
                    sb.AppendLine($"{indent}        {varKeyword}{element.LocalName} = {tempNames[index]};");
                }
            }
        }
        else
        {
            var isHoisted = hoistedTypes.Contains(handle.Returns[0].FullType);
            var varKeyword = isHoisted ? "" : "var ";
            sb.AppendLine($"{indent}        {varKeyword}{handle.Returns[0].LocalName} = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");
        }

        BuildValidationResultChecks(sb, handle.Returns, taskWrap, taskClose, indent);
        BuildNotFoundChecks(sb, model, handle.Returns, taskWrap, taskClose, indent);
        var firstReturn = handle.Returns[0];
        var firstLocal = model.LocalVariables.FirstOrDefault(l => l.FullType == firstReturn.FullType);
        return firstLocal?.CheckNullability == true ? firstReturn.NonNullLocalName : firstReturn.LocalName;
    }

    private static IEnumerable<string> BuildCallArguments(MethodPhase phase, EquatableArray<LocalVariable> returnElements)
    {
        foreach (var parameter in phase.Parameters)
        {
            if (parameter.IsFromServices)
            {
                yield return parameter.IsNullable
                    ? $"_serviceProvider.GetService<{parameter.FullType}>()"
                    : $"_serviceProvider.GetRequiredService<{parameter.FullType}>()";
                continue;
            }

            yield return returnElements
                .Single(local => local.FullType == parameter.FullType)
                .LocalName;
        }
    }

    private static void BuildFinallyPhase(StringBuilder sb, HandlerModel model, MethodPhase finallyPhase, string indent, IReadOnlyDictionary<string, string> hoistedLocalNames, IReadOnlyDictionary<string, string> middlewareFieldNames)
    {
        var awaitPrefix = finallyPhase.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildFinallyCallArguments(finallyPhase, model.LocalVariables, hoistedLocalNames));
        var methodTarget = GetMethodTarget(model, finallyPhase, middlewareFieldNames);
        sb.AppendLine($"{indent}            {awaitPrefix}{methodTarget}.{finallyPhase.MethodName}({callArguments});");
    }

    private static IEnumerable<string> BuildFinallyCallArguments(
        MethodPhase finallyPhase,
        EquatableArray<LocalVariable> localVariables,
        IReadOnlyDictionary<string, string> hoistedLocalNames)
    {
        foreach (var parameter in finallyPhase.Parameters)
        {
            if (parameter.IsFromServices)
            {
                yield return parameter.IsNullable
                    ? $"_serviceProvider.GetService<{parameter.FullType}>()"
                    : $"_serviceProvider.GetRequiredService<{parameter.FullType}>()";
                continue;
            }

            if (hoistedLocalNames.TryGetValue(parameter.FullType, out var hoistedLocalName))
            {
                yield return hoistedLocalName;
                continue;
            }

            yield return localVariables
                .Single(local => local.FullType == parameter.FullType)
                .LocalName;
        }
    }
}
