using Caravelle.Generator.Handler;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Caravelle.Generator.SourceBuilders;

public static class RegistrationsSourceBuilder
{
    public static string Build(
        HandlerModel[] models,
        HashSet<string> conflicting,
        HashSet<string> excludedDispatcherPairs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace Caravelle");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedHandlerRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGeneratedHandlers(");
        sb.AppendLine("            this IServiceCollection services)");
        sb.AppendLine("        {");

        // Register each distinct non-static middleware type exactly once, even when matched
        // to many handlers — static middleware methods are called directly via their type
        // name and never need a DI-resolved instance.
        var middlewareTypes = models
            .Where(model => !excludedDispatcherPairs.Contains(model.DispatcherKey))
            .SelectMany(static model => model.Phases.Concat(model.FinallyPhases))
            .Where(static phase => phase.OwnerTypeFullName is not null && !phase.IsStatic)
            .Select(static phase => phase.OwnerTypeFullName!)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static type => type, StringComparer.Ordinal)
            .ToArray();

        foreach (var middlewareType in middlewareTypes)
            sb.AppendLine($"            services.AddTransient<{middlewareType}>();");

        foreach (var model in models)
        {
            if (excludedDispatcherPairs.Contains(model.DispatcherKey))
                continue;

            if (model.HasInstanceMethods)
                sb.AppendLine($"            services.AddTransient<{model.FullClassName}>();");

            sb.AppendLine($"            services.AddTransient<");
            sb.AppendLine($"                global::Caravelle.IDispatcher<");
            sb.AppendLine($"                    {model.FullRequestType},");
            sb.AppendLine($"                    {model.ResultTypeName}>,");
            sb.AppendLine($"                {model.DispatcherFullName}>();");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // ── Typed Caravelle extension methods ──────────────────────────────");
        sb.AppendLine("    public static class CaravelleExtensions");
        sb.AppendLine("    {");

        foreach (var model in models)
        {
            if (excludedDispatcherPairs.Contains(model.DispatcherKey))
            {
                continue;
            }
            if (conflicting.Contains(model.FullRequestType)) continue;
            sb.AppendLine($"        public static global::System.Threading.Tasks.Task<{model.ResultTypeName}>");
            sb.AppendLine($"            Handle(this global::Caravelle.Bus bus, {model.FullRequestType} request)");
            sb.AppendLine($"            => bus.Handle<{model.FullRequestType}, {model.ResultTypeName}>(request);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
