using Microsoft.Extensions.DependencyInjection;

namespace Caravelle;

public static class ServiceCollectionExtensions
{
    /// <summary>
    /// Registers the core <see cref="Bus"/> service.
    /// You must also call <c>AddGeneratedHandlers()</c> (generated by Caravelle.Generator)
    /// to register your handler dispatchers and typed extension methods.
    /// </summary>
    public static IServiceCollection AddCaravelleCore(this IServiceCollection services)
    {
        services.AddTransient<Bus>();
        return services;
    }
}
