using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MiniBus.Generator;

public static class DispatcherSourceBuilder
{
    public static string Build(HandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.HasFromServicesParameters)
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // ── Dispatcher class ─────────────────────────────────────────────────
        var inNs = model.Namespace is not null;
        var i = inNs ? "    " : "";     // indent when inside a namespace block
        var asyncKeyword = model.IsAnyAsync ? "async " : "";
        var taskWrap = model.IsAnyAsync ? "" : "global::System.Threading.Tasks.Task.FromResult(";
        var taskClose = model.IsAnyAsync ? "" : ")";

        if (inNs) { sb.AppendLine($"namespace {model.Namespace}"); sb.AppendLine("{"); }

        sb.AppendLine($"{i}public sealed class {model.ClassName}Dispatcher");
        sb.AppendLine($"{i}    : global::MiniBus.IDispatcher<");
        sb.AppendLine($"{i}        {model.FullRequestType},");
        sb.AppendLine($"{i}        {model.ClassName}Dispatcher.Result>");
        sb.AppendLine($"{i}{{");

        ResultTypeSourceBuilder.Build(sb, model, i);

        if (model.HasInstanceMethods)
            sb.AppendLine($"{i}    private readonly {model.FullClassName} _handler;");
        if (model.HasFromServicesParameters)
            sb.AppendLine($"{i}    private readonly global::System.IServiceProvider _serviceProvider;");

        if (model.HasInstanceMethods || model.HasFromServicesParameters)
        {
            sb.AppendLine();

            var ctorParameters = new List<string>();
            if (model.HasInstanceMethods)
                ctorParameters.Add($"{model.FullClassName} handler");
            if (model.HasFromServicesParameters)
                ctorParameters.Add("global::System.IServiceProvider serviceProvider");

            sb.AppendLine($"{i}    public {model.ClassName}Dispatcher({string.Join(", ", ctorParameters)})");
            sb.AppendLine($"{i}    {{");
            if (model.HasInstanceMethods)
                sb.AppendLine($"{i}        _handler = handler;");
            if (model.HasFromServicesParameters)
                sb.AppendLine($"{i}        _serviceProvider = serviceProvider;");
            sb.AppendLine($"{i}    }}");
        }

        sb.AppendLine();
        sb.AppendLine($"{i}    public string HandlerName => nameof({model.FullClassName});");
        sb.AppendLine();
        sb.AppendLine($"{i}    public {asyncKeyword}global::System.Threading.Tasks.Task<Result>");
        sb.AppendLine($"{i}        Handle({model.FullRequestType} request)");
        sb.AppendLine($"{i}    {{");

        // Hoist variables needed by Finally before try block
        var hoistedTypes = new HashSet<string>(StringComparer.Ordinal);
        var hoistedLocalNames = new Dictionary<string, string>(StringComparer.Ordinal);
        if (model.FinallyPhase is not null)
        {
            var returnLocalsByType = model.Phases
                .SelectMany(phase => phase.Returns)
                .GroupBy(element => element.FullType)
                .ToDictionary(group => group.Key, group => group.First().LocalName, StringComparer.Ordinal);

            foreach (var param in model.FinallyPhase.Parameters)
            {
                if (!param.IsFromServices && returnLocalsByType.TryGetValue(param.FullType, out var nullableLocalName))
                {
                    hoistedTypes.Add(param.FullType);
                    hoistedLocalNames[param.FullType] = nullableLocalName;
                    sb.AppendLine($"{i}        {param.FullType}? {nullableLocalName} = null;");
                }
            }
            if (hoistedTypes.Count > 0)
                sb.AppendLine();
        }

        // Start try block if Finally exists
        if (model.FinallyPhase is not null)
        {
            sb.AppendLine($"{i}        try");
            sb.AppendLine($"{i}        {{");
        }

        string? responseLocalName = null;
        var phaseIndent = model.FinallyPhase is not null ? i + "    " : i;

        foreach (var phase in model.Phases)
        {
            switch (phase.Type)
            {
                case PhaseType.Before:
                    BuildPipelinePhase(sb, model, phase, taskWrap, taskClose, phaseIndent, hoistedTypes);
                    break;
                case PhaseType.Handle:
                    responseLocalName = BuildHandlePhase(sb, model, phase, taskWrap, taskClose, phaseIndent, hoistedTypes);
                    break;
                case PhaseType.After:
                    BuildPipelinePhase(sb, model, phase, taskWrap, taskClose, phaseIndent, hoistedTypes);
                    break;
            }
        }

        var returnIndent = model.FinallyPhase is not null ? i + "            " : i + "        ";
        sb.AppendLine($"{returnIndent}return {taskWrap}new Result({responseLocalName ?? "default!"}){taskClose};");

        // Close try and add finally
        if (model.FinallyPhase is not null)
        {
            sb.AppendLine($"{i}        }}");
            sb.AppendLine($"{i}        finally");
            sb.AppendLine($"{i}        {{");
            BuildFinallyPhase(sb, model, model.FinallyPhase, i, hoistedLocalNames);
            sb.AppendLine($"{i}        }}");
        }

        sb.AppendLine($"{i}    }}");
        sb.AppendLine($"{i}}}");
        if (inNs) sb.AppendLine("}");

        return sb.ToString();
    }

    private static void BuildPipelinePhase(StringBuilder sb, HandlerModel model, MethodPhase phase, string taskWrap, string taskClose, string indent, HashSet<string> hoistedTypes)
    {
        var awaitPrefix = phase.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(phase, model.LocalVariables));
        var methodTarget = phase.IsStatic ? model.FullClassName : "_handler";
        if (phase.Returns.Count > 1)
        {
            var hasHoistedReturns = phase.Returns.Any(e => hoistedTypes.Contains(e.FullType));
            if (!hasHoistedReturns)
            {
                var varNames = string.Join(", ", phase.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        var ({varNames}) = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");
            }
            else if (phase.Returns.All(e => hoistedTypes.Contains(e.FullType)))
            {
                var varNames = string.Join(", ", phase.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        ({varNames}) = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");
            }
            else
            {
                var tempNames = phase.Returns
                    .Select((_, index) => $"__{phase.MethodName}Result{index}")
                    .ToArray();
                sb.AppendLine($"{indent}        var ({string.Join(", ", tempNames)}) = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");

                for (var index = 0; index < phase.Returns.Count; index++)
                {
                    var element = phase.Returns[index];
                    var varKeyword = hoistedTypes.Contains(element.FullType) ? "" : "var ";
                    sb.AppendLine($"{indent}        {varKeyword}{element.LocalName} = {tempNames[index]};");
                }
            }
        }
        else
        {
            var isHoisted = hoistedTypes.Contains(phase.Returns[0].FullType);
            var varKeyword = isHoisted ? "" : "var ";
            sb.AppendLine($"{indent}        {varKeyword}{phase.Returns[0].LocalName} = {awaitPrefix}{methodTarget}.{phase.MethodName}({callArguments});");
        }

        BuildValidationResultChecks(sb, phase.Returns, taskWrap, taskClose, indent);
        BuildNotFoundChecks(sb, model, phase.Returns, taskWrap, taskClose, indent);

        sb.AppendLine();
    }

    private static void BuildValidationResultChecks(StringBuilder sb, EquatableArray<ReturnElement> returnValues, string taskWrap, string taskClose, string indent)
    {
        foreach (var element in returnValues)
        {
            if (element.IsResultType)
            {
                var validationResultLocalName = $"{element.LocalName}ValidationResult";
                sb.AppendLine($"{indent}        if ({element.LocalName} is global::MiniBus.IValidationResult {validationResultLocalName} && !{validationResultLocalName}.IsValid())");
                sb.AppendLine($"{indent}            return {taskWrap}new Result({element.LocalName}){taskClose};");
            }
        }
    }

    private static void BuildNotFoundChecks(StringBuilder sb, HandlerModel model, EquatableArray<ReturnElement> returnValues, string taskWrap, string taskClose, string indent)
    {
        foreach (var element in returnValues)
        {
            var local = model.LocalVariables.First(l => l.FullType == element.FullType);
            if (local.CheckNullability)
            {
                var ifNullMessage = local.IfNullErrorMessage is null ? "notfound" : $"\"{local.IfNullErrorMessage}\"";
                sb.AppendLine($"{indent}        if ({element.LocalName} is not {{ }} {element.NonNullLocalName})");
                sb.AppendLine($"{indent}            return {taskWrap}new Result(new global::MiniBus.NotFoundResult({ifNullMessage})){taskClose};");
            }
        }
    }

    private static string BuildHandlePhase(StringBuilder sb, HandlerModel model, MethodPhase handle, string taskWrap, string taskClose, string indent, HashSet<string> hoistedTypes)
    {
        var handleAwait = handle.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(handle, model.LocalVariables));
        var methodTarget = handle.IsStatic ? model.FullClassName : "_handler";

        if (handle.Returns.Count > 1)
        {
            var hasHoistedReturns = handle.Returns.Any(e => hoistedTypes.Contains(e.FullType));
            if (!hasHoistedReturns)
            {
                var varNames = string.Join(", ", handle.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        var ({varNames}) = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");
            }
            else if (handle.Returns.All(e => hoistedTypes.Contains(e.FullType)))
            {
                var varNames = string.Join(", ", handle.Returns.Select(e => e.LocalName));
                sb.AppendLine($"{indent}        ({varNames}) = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");
            }
            else
            {
                var tempNames = handle.Returns
                    .Select((_, index) => $"__{handle.MethodName}Result{index}")
                    .ToArray();
                sb.AppendLine($"{indent}        var ({string.Join(", ", tempNames)}) = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");

                for (var index = 0; index < handle.Returns.Count; index++)
                {
                    var element = handle.Returns[index];
                    var varKeyword = hoistedTypes.Contains(element.FullType) ? "" : "var ";
                    sb.AppendLine($"{indent}        {varKeyword}{element.LocalName} = {tempNames[index]};");
                }
            }
        }
        else
        {
            var isHoisted = hoistedTypes.Contains(handle.Returns[0].FullType);
            var varKeyword = isHoisted ? "" : "var ";
            sb.AppendLine($"{indent}        {varKeyword}{handle.Returns[0].LocalName} = {handleAwait}{methodTarget}.{handle.MethodName}({callArguments});");
        }

        BuildValidationResultChecks(sb, handle.Returns, taskWrap, taskClose, indent);
        BuildNotFoundChecks(sb, model, handle.Returns, taskWrap, taskClose, indent);
        var firstReturn = handle.Returns[0];
        var firstLocal = model.LocalVariables.FirstOrDefault(l => l.FullType == firstReturn.FullType);
        return firstLocal?.CheckNullability == true ? firstReturn.NonNullLocalName : firstReturn.LocalName;
    }

    private static IEnumerable<string> BuildCallArguments(MethodPhase phase, EquatableArray<LocalVariable> returnElements)
    {
        foreach (var parameter in phase.Parameters)
        {
            if (parameter.IsFromServices)
            {
                yield return parameter.IsNullable
                    ? $"_serviceProvider.GetService<{parameter.FullType}>()"
                    : $"_serviceProvider.GetRequiredService<{parameter.FullType}>()";
                continue;
            }

            yield return returnElements
                .Single(local => local.FullType == parameter.FullType)
                .LocalName;
        }
    }

    private static void BuildFinallyPhase(StringBuilder sb, HandlerModel model, MethodPhase finallyPhase, string indent, IReadOnlyDictionary<string, string> hoistedLocalNames)
    {
        var awaitPrefix = finallyPhase.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildFinallyCallArguments(finallyPhase, model.LocalVariables, hoistedLocalNames));
        var methodTarget = finallyPhase.IsStatic ? model.FullClassName : "_handler";
        sb.AppendLine($"{indent}            {awaitPrefix}{methodTarget}.{finallyPhase.MethodName}({callArguments});");
    }

    private static IEnumerable<string> BuildFinallyCallArguments(
        MethodPhase finallyPhase,
        EquatableArray<LocalVariable> localVariables,
        IReadOnlyDictionary<string, string> hoistedLocalNames)
    {
        foreach (var parameter in finallyPhase.Parameters)
        {
            if (parameter.IsFromServices)
            {
                yield return parameter.IsNullable
                    ? $"_serviceProvider.GetService<{parameter.FullType}>()"
                    : $"_serviceProvider.GetRequiredService<{parameter.FullType}>()";
                continue;
            }

            if (hoistedLocalNames.TryGetValue(parameter.FullType, out var hoistedLocalName))
            {
                yield return hoistedLocalName;
                continue;
            }

            yield return localVariables
                .Single(local => local.FullType == parameter.FullType)
                .LocalName;
        }
    }
}
