using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;

namespace MiniBus.Generator;

public static class DispatcherSourceBuilder
{
    public static string Build(HandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // ── Dispatcher class ─────────────────────────────────────────────────
        var inNs = model.Namespace is not null;
        var i = inNs ? "    " : "";     // indent when inside a namespace block
        var asyncKeyword = model.IsAnyAsync ? "async " : "";
        var taskWrap = model.IsAnyAsync ? "" : "global::System.Threading.Tasks.Task.FromResult(";
        var taskClose = model.IsAnyAsync ? "" : ")";

        if (inNs) { sb.AppendLine($"namespace {model.Namespace}"); sb.AppendLine("{"); }

        sb.AppendLine($"{i}public class {model.ClassName}Dispatcher");
        sb.AppendLine($"{i}    : global::MiniBus.IDispatcher<");
        sb.AppendLine($"{i}        {model.FullRequestType},");
        sb.AppendLine($"{i}        {model.FullResponseType}>");
        sb.AppendLine($"{i}{{");
        sb.AppendLine($"{i}    private readonly {model.FullClassName} _handler;");
        sb.AppendLine();
        sb.AppendLine($"{i}    public {model.ClassName}Dispatcher({model.FullClassName} handler)");
        sb.AppendLine($"{i}    {{");
        sb.AppendLine($"{i}        _handler = handler;");
        sb.AppendLine($"{i}    }}");
        sb.AppendLine();
        sb.AppendLine($"{i}    public string HandlerName => nameof({model.FullClassName});");
        sb.AppendLine();
        sb.AppendLine($"{i}    public {asyncKeyword}global::System.Threading.Tasks.Task<");
        sb.AppendLine($"{i}        global::MiniBus.Result<{model.FullResponseType}>>");
        sb.AppendLine($"{i}        Handle({model.FullRequestType} request)");
        sb.AppendLine($"{i}    {{");

        foreach (var phase in model.Phases)
        {
            switch (phase.Type)
            {
                case PhaseType.Before:
                    BuildPrePhase(sb, model, phase, taskWrap, taskClose, i);
                    break;
                case PhaseType.Handle:
                    BuildHandlePhase(sb, model, phase, taskWrap, taskClose, i);
                    break;
                default: break;
            }
        }

        sb.AppendLine($"{i}    }}");
        sb.AppendLine($"{i}}}");
        if (inNs) sb.AppendLine("}");

        return sb.ToString();
    }

    private static void BuildPrePhase(StringBuilder sb, HandlerModel model, MethodPhase prePhase, string taskWrap, string taskClose, string indent)
    {
        var awaitPrefix = prePhase.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(prePhase, model.LocalVariables));
        if (prePhase.Returns.Length > 1)
        {
            var varNames = string.Join(", ", prePhase.Returns.Select(e => e.LocalName));
            sb.AppendLine($"{indent}        var ({varNames}) = {awaitPrefix}_handler.{prePhase.MethodName}({callArguments});");
        }
        else
        {
            sb.AppendLine($"{indent}        var {prePhase.Returns[0].LocalName} = {awaitPrefix}_handler.{prePhase.MethodName}({callArguments});");
        }

        BuildReturnValueChecks(sb, model, prePhase.Returns, taskWrap, taskClose, indent);

        sb.AppendLine();
    }

    private static void BuildReturnValueChecks(StringBuilder sb, HandlerModel model, ImmutableArray<ReturnElement> returnValues, string taskWrap, string taskClose, string indent)
    {
        foreach (var element in returnValues)
        {
            var local = model.LocalVariables.First(l => l.FullType == element.FullType);

            if (element.IsValidationResult)
            {
                sb.AppendLine($"{indent}        if (!{element.NonNullLocalName}.IsValid())");
                sb.AppendLine($"{indent}            return {taskWrap}global::MiniBus.Result<{model.FullResponseType}>.Invalid({element.NonNullLocalName}){taskClose};");
            }

            if (local.CheckNullability)
            {
                var ifNullMessage = local.IfNullErrorMessage is null ? null : $"\"{local.IfNullErrorMessage}\"";
                sb.AppendLine($"{indent}        if ({element.LocalName} is not {{ }} {element.NonNullLocalName})");
                sb.AppendLine($"{indent}            return {taskWrap}global::MiniBus.Result<{model.FullResponseType}>.NotFound({ifNullMessage}){taskClose};");
            }
        }
    }

    private static void BuildHandlePhase(StringBuilder sb, HandlerModel model, MethodPhase handle, string taskWrap, string taskClose, string indent)
    {
        var handleAwait = handle.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(handle, model.LocalVariables));
        sb.AppendLine($"{indent}        var response = {handleAwait}_handler.Handle({callArguments});");
        sb.AppendLine($"{indent}        return {taskWrap}global::MiniBus.Result<{model.FullResponseType}>.Success(response){taskClose};");
    }

    private static IEnumerable<string> BuildCallArguments(MethodPhase phase, ImmutableArray<LocalVariable> returnElements)
    {
        foreach (var parameter in phase.Parameters)
        {
            yield return returnElements
                .Single(local => local.FullType == parameter.FullType)
                .LocalName;
        }
    }
}
