using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace MiniBus.Generator;

public static class DispatcherSourceBuilder
{
    public static string Build(HandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        if (model.HasFromServicesParameters)
            sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        // ── Dispatcher class ─────────────────────────────────────────────────
        var inNs = model.Namespace is not null;
        var i = inNs ? "    " : "";     // indent when inside a namespace block
        var asyncKeyword = model.IsAnyAsync ? "async " : "";
        var taskWrap = model.IsAnyAsync ? "" : "global::System.Threading.Tasks.Task.FromResult(";
        var taskClose = model.IsAnyAsync ? "" : ")";

        if (inNs) { sb.AppendLine($"namespace {model.Namespace}"); sb.AppendLine("{"); }

        sb.AppendLine($"{i}public class {model.ClassName}Dispatcher");
        sb.AppendLine($"{i}    : global::MiniBus.IDispatcher<");
        sb.AppendLine($"{i}        {model.FullRequestType},");
        sb.AppendLine($"{i}        {model.FullResponseType}>");
        sb.AppendLine($"{i}{{");

        if (model.HasInstanceMethods)
            sb.AppendLine($"{i}    private readonly {model.FullClassName} _handler;");
        if (model.HasFromServicesParameters)
            sb.AppendLine($"{i}    private readonly global::System.IServiceProvider _serviceProvider;");

        if (model.HasInstanceMethods || model.HasFromServicesParameters)
        {
            sb.AppendLine();

            var ctorParameters = new List<string>();
            if (model.HasInstanceMethods)
                ctorParameters.Add($"{model.FullClassName} handler");
            if (model.HasFromServicesParameters)
                ctorParameters.Add("global::System.IServiceProvider serviceProvider");

            sb.AppendLine($"{i}    public {model.ClassName}Dispatcher({string.Join(", ", ctorParameters)})");
            sb.AppendLine($"{i}    {{");
            if (model.HasInstanceMethods)
                sb.AppendLine($"{i}        _handler = handler;");
            if (model.HasFromServicesParameters)
                sb.AppendLine($"{i}        _serviceProvider = serviceProvider;");
            sb.AppendLine($"{i}    }}");
        }

        sb.AppendLine();
        sb.AppendLine($"{i}    public string HandlerName => nameof({model.FullClassName});");
        sb.AppendLine();
        sb.AppendLine($"{i}    public {asyncKeyword}global::System.Threading.Tasks.Task<");
        sb.AppendLine($"{i}        global::MiniBus.Result<{model.FullResponseType}>>");
        sb.AppendLine($"{i}        Handle({model.FullRequestType} request)");
        sb.AppendLine($"{i}    {{");

        foreach (var phase in model.Phases)
        {
            switch (phase.Type)
            {
                case PhaseType.Before:
                    BuildPrePhase(sb, model, phase, taskWrap, taskClose, i);
                    break;
                case PhaseType.Handle:
                    BuildHandlePhase(sb, model, phase, taskWrap, taskClose, i);
                    break;
            }
        }

        sb.AppendLine($"{i}    }}");
        sb.AppendLine($"{i}}}");
        if (inNs) sb.AppendLine("}");

        return sb.ToString();
    }

    private static void BuildPrePhase(StringBuilder sb, HandlerModel model, MethodPhase prePhase, string taskWrap, string taskClose, string indent)
    {
        var awaitPrefix = prePhase.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(prePhase, model.LocalVariables));
        var methodTarget = prePhase.IsStatic ? model.FullClassName : "_handler";
        if (prePhase.Returns.Count > 1)
        {
            var varNames = string.Join(", ", prePhase.Returns.Select(e => e.LocalName));
            sb.AppendLine($"{indent}        var ({varNames}) = {awaitPrefix}{methodTarget}.{prePhase.MethodName}({callArguments});");
        }
        else
        {
            sb.AppendLine($"{indent}        var {prePhase.Returns[0].LocalName} = {awaitPrefix}{methodTarget}.{prePhase.MethodName}({callArguments});");
        }

        BuildReturnValueChecks(sb, model, prePhase.Returns, taskWrap, taskClose, indent);

        sb.AppendLine();
    }

    private static void BuildReturnValueChecks(StringBuilder sb, HandlerModel model, EquatableArray<ReturnElement> returnValues, string taskWrap, string taskClose, string indent)
    {
        foreach (var element in returnValues)
        {
            var local = model.LocalVariables.First(l => l.FullType == element.FullType);

            if (element.IsValidationResult)
            {
                sb.AppendLine($"{indent}        if (!{element.NonNullLocalName}.IsValid())");
                sb.AppendLine($"{indent}            return {taskWrap}global::MiniBus.Result<{model.FullResponseType}>.Invalid({element.NonNullLocalName}){taskClose};");
            }

            if (local.CheckNullability)
            {
                var ifNullMessage = local.IfNullErrorMessage is null ? null : $"\"{local.IfNullErrorMessage}\"";
                sb.AppendLine($"{indent}        if ({element.LocalName} is not {{ }} {element.NonNullLocalName})");
                sb.AppendLine($"{indent}            return {taskWrap}global::MiniBus.Result<{model.FullResponseType}>.NotFound({ifNullMessage}){taskClose};");
            }
        }
    }

    private static void BuildHandlePhase(StringBuilder sb, HandlerModel model, MethodPhase handle, string taskWrap, string taskClose, string indent)
    {
        var handleAwait = handle.IsAsync ? "await " : "";
        var callArguments = string.Join(", ", BuildCallArguments(handle, model.LocalVariables));
        var methodTarget = handle.IsStatic ? model.FullClassName : "_handler";
        sb.AppendLine($"{indent}        var response = {handleAwait}{methodTarget}.Handle({callArguments});");
        sb.AppendLine($"{indent}        return {taskWrap}global::MiniBus.Result<{model.FullResponseType}>.Success(response){taskClose};");
    }

    private static IEnumerable<string> BuildCallArguments(MethodPhase phase, EquatableArray<LocalVariable> returnElements)
    {
        foreach (var parameter in phase.Parameters)
        {
            if (parameter.IsFromServices)
            {
                yield return parameter.IsNullable
                    ? $"_serviceProvider.GetService<{parameter.FullType}>()"
                    : $"_serviceProvider.GetRequiredService<{parameter.FullType}>()";
                continue;
            }

            yield return returnElements
                .Single(local => local.FullType == parameter.FullType)
                .LocalName;
        }
    }
}
