using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace MiniBus.Generator;

internal sealed record HandlerModel(
    string? Namespace,
    string ClassName,
    string FullClassName,
    string FullRequestType,
    string FullResponseType)
{
    // "global::TestApp.DummyHandler" + "Dispatcher" = "global::TestApp.DummyHandlerDispatcher"
    public string DispatcherFullName => FullClassName + "Dispatcher";
}

[Generator]
public class HandlerGenerator : IIncrementalGenerator
{
    private const string HandlerAttributeFqn = "MiniBus.Convention.HandlerAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlerModels = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                HandlerAttributeFqn,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, ct) => GetHandlerModel(ctx, ct))
            .Where(static m => m is not null);

        // One file per handler: dispatcher class + typed ConventionBus extension method
        context.RegisterSourceOutput(handlerModels, static (spc, model) =>
        {
            if (model is null) return;
            spc.AddSource($"{model.ClassName}Dispatcher.g.cs", GenerateDispatcherSource(model));
        });

        // One file for all handlers: AddGeneratedHandlers() DI registration
        context.RegisterSourceOutput(handlerModels.Collect(), static (spc, models) =>
        {
            var valid = models
                .Where(static m => m is not null)
                .Select(static m => m!)
                .ToArray();
            if (valid.Length == 0) return;   // no handlers → no file (avoids noise in tests)
            spc.AddSource("ConventionRegistrations.g.cs", GenerateRegistrationsSource(valid));
        });
    }

    private static HandlerModel? GetHandlerModel(GeneratorAttributeSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol classSymbol) return null;
        ct.ThrowIfCancellationRequested();

        // Must have a nested type named "Request"
        var requestType = classSymbol.GetTypeMembers()
            .FirstOrDefault(static t => t.Name == "Request");
        if (requestType is null) return null;

        // Must have a non-static Handle method with at least one parameter
        var handleMethod = classSymbol.GetMembers("Handle")
            .OfType<IMethodSymbol>()
            .FirstOrDefault(static m => !m.IsStatic && m.Parameters.Length >= 1);
        if (handleMethod is null) return null;

        // Unwrap Task<T> → T to determine TResponse
        var returnType = handleMethod.ReturnType;
        ITypeSymbol responseType;
        if (returnType is INamedTypeSymbol namedReturn
            && namedReturn.Name == "Task"
            && namedReturn.TypeArguments.Length == 1)
        {
            responseType = namedReturn.TypeArguments[0];
        }
        else
        {
            responseType = returnType;
        }

        var fmt = SymbolDisplayFormat.FullyQualifiedFormat;
        var ns = classSymbol.ContainingNamespace.IsGlobalNamespace
            ? null
            : classSymbol.ContainingNamespace.ToDisplayString();

        return new HandlerModel(
            Namespace: ns,
            ClassName: classSymbol.Name,
            FullClassName: classSymbol.ToDisplayString(fmt),
            FullRequestType: requestType.ToDisplayString(fmt),
            FullResponseType: responseType.ToDisplayString(fmt));
    }

    private static string GenerateDispatcherSource(HandlerModel model)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        // ── Dispatcher class ─────────────────────────────────────────────────
        var inNs = model.Namespace is not null;
        var i = inNs ? "    " : "";     // indent when inside a namespace block

        if (inNs) { sb.AppendLine($"namespace {model.Namespace}"); sb.AppendLine("{"); }

        sb.AppendLine($"{i}public class {model.ClassName}Dispatcher");
        sb.AppendLine($"{i}    : global::MiniBus.Convention.IConventionHandler<");
        sb.AppendLine($"{i}        {model.FullRequestType},");
        sb.AppendLine($"{i}        {model.FullResponseType}>");
        sb.AppendLine($"{i}{{");
        sb.AppendLine($"{i}    private readonly {model.FullClassName} _handler;");
        sb.AppendLine();
        sb.AppendLine($"{i}    public {model.ClassName}Dispatcher({model.FullClassName} handler)");
        sb.AppendLine($"{i}    {{");
        sb.AppendLine($"{i}        _handler = handler;");
        sb.AppendLine($"{i}    }}");
        sb.AppendLine();
        sb.AppendLine($"{i}    public async global::System.Threading.Tasks.Task<");
        sb.AppendLine($"{i}        global::MiniBus.Convention.Result<{model.FullResponseType}>>");
        sb.AppendLine($"{i}        Handle({model.FullRequestType} request)");
        sb.AppendLine($"{i}    {{");
        sb.AppendLine($"{i}        var response = await _handler.Handle(request);");
        sb.AppendLine($"{i}        return global::MiniBus.Convention.Result<{model.FullResponseType}>.Success(response);");
        sb.AppendLine($"{i}    }}");
        sb.AppendLine($"{i}}}");

        if (inNs) sb.AppendLine("}");

        // ── Typed ConventionBus extension method ─────────────────────────────
        sb.AppendLine();
        sb.AppendLine("namespace MiniBus.Convention");
        sb.AppendLine("{");
        sb.AppendLine($"    public static class {model.ClassName}Extensions");
        sb.AppendLine("    {");
        sb.AppendLine($"        public static global::System.Threading.Tasks.Task<global::MiniBus.Convention.Result<{model.FullResponseType}>>");
        sb.AppendLine($"            Handle(this global::MiniBus.Convention.ConventionBus bus, {model.FullRequestType} request)");
        sb.AppendLine($"            => bus.Handle<{model.FullRequestType}, {model.FullResponseType}>(request);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string GenerateRegistrationsSource(HandlerModel[] models)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace MiniBus.Convention");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedHandlerRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGeneratedHandlers(");
        sb.AppendLine("            this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            services.AddScoped<{model.FullClassName}>();");
            sb.AppendLine($"            services.AddScoped<");
            sb.AppendLine($"                global::MiniBus.Convention.IConventionHandler<");
            sb.AppendLine($"                    {model.FullRequestType},");
            sb.AppendLine($"                    {model.FullResponseType}>,");
            sb.AppendLine($"                {model.DispatcherFullName}>();");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}

