using System.Text;

namespace MiniBus.Generator;

public static class RegistrationsSourceBuilder
{
    public static string Build(
        HandlerModel[] models,
        System.Collections.Generic.HashSet<string> conflicting)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace MiniBus.Convention");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedHandlerRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGeneratedHandlers(");
        sb.AppendLine("            this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            sb.AppendLine($"            services.AddScoped<{model.FullClassName}>();");
            sb.AppendLine($"            services.AddScoped<");
            sb.AppendLine($"                global::MiniBus.Convention.IConventionHandler<");
            sb.AppendLine($"                    {model.FullRequestType},");
            sb.AppendLine($"                    {model.FullResponseType}>,");
            sb.AppendLine($"                {model.DispatcherFullName}>();");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // ── Typed ConventionBus extension methods ──────────────────────────────");
        sb.AppendLine("    public static class ConventionBusExtensions");
        sb.AppendLine("    {");

        foreach (var model in models)
        {
            if (conflicting.Contains(model.FullRequestType)) continue;
            sb.AppendLine($"        public static global::System.Threading.Tasks.Task<global::MiniBus.Convention.Result<{model.FullResponseType}>>");
            sb.AppendLine($"            Handle(this global::MiniBus.Convention.ConventionBus bus, {model.FullRequestType} request)");
            sb.AppendLine($"            => bus.Handle<{model.FullRequestType}, {model.FullResponseType}>(request);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
