using System.Text;

namespace MiniBus.Generator;

public static class RegistrationsSourceBuilder
{
    public static string Build(
        HandlerModel[] models,
        System.Collections.Generic.HashSet<string> conflicting,
        System.Collections.Generic.HashSet<string> excludedDispatcherPairs)
    {
        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("namespace MiniBus");
        sb.AppendLine("{");
        sb.AppendLine("    public static class GeneratedHandlerRegistrations");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGeneratedHandlers(");
        sb.AppendLine("            this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var model in models)
        {
            if (excludedDispatcherPairs.Contains(model.DispatcherKey))
                continue;

            if (model.HasInstanceMethods)
                sb.AppendLine($"            services.AddTransient<{model.FullClassName}>();");

            sb.AppendLine($"            services.AddTransient<");
            sb.AppendLine($"                global::MiniBus.IDispatcher<");
            sb.AppendLine($"                    {model.FullRequestType},");
            sb.AppendLine($"                    {model.DispatcherFullName}.Result>,");
            sb.AppendLine($"                {model.DispatcherFullName}>();");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    // ── Typed MiniBus extension methods ──────────────────────────────");
        sb.AppendLine("    public static class MiniBusExtensions");
        sb.AppendLine("    {");

        foreach (var model in models)
        {
            if (excludedDispatcherPairs.Contains(model.DispatcherKey))
            {
                continue;
            }
            if (conflicting.Contains(model.FullRequestType)) continue;
            sb.AppendLine($"        public static global::System.Threading.Tasks.Task<{model.DispatcherFullName}.Result>");
            sb.AppendLine($"            Handle(this global::MiniBus.MiniBus bus, {model.FullRequestType} request)");
            sb.AppendLine($"            => bus.Handle<{model.FullRequestType}, {model.DispatcherFullName}.Result>(request);");
        }

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
