//HintName: InheritedMiddlewareHandlerDispatcher_bc9ed4af.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class InheritedMiddlewareHandlerDispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.Request,
            global::TestApp.Response>
    {
        private readonly global::TestApp.InheritedMiddlewareHandler _handler;

        public InheritedMiddlewareHandlerDispatcher(global::TestApp.InheritedMiddlewareHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.InheritedMiddlewareHandler);

        public async global::System.Threading.Tasks.Task<global::TestApp.Response>
            Handle(global::TestApp.Request request)
        {
            try
            {
                var fromBeforeAudit = _handler.BeforeAudit(request);

                var fromHandle = await _handler.Handle(request, fromBeforeAudit);
                var fromAfterLog = _handler.AfterLog(fromHandle);

                return fromHandle;
            }
            finally
            {
                await _handler.FinallyAsync(request);
                _handler.Finally(request);
            }
        }
    }
}
