//HintName: CaravelleRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Caravelle
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.InheritedMiddlewareHandler>();
            services.AddTransient<
                global::Caravelle.IDispatcher<
                    global::TestApp.Request,
                    global::TestApp.Response>,
                global::TestApp.InheritedMiddlewareHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed Caravelle extension methods ──────────────────────────────
    public static class CaravelleExtensions
    {
        public static global::System.Threading.Tasks.Task<global::TestApp.Response>
            Handle(this global::Caravelle.Bus bus, global::TestApp.Request request)
            => bus.Handle<global::TestApp.Request, global::TestApp.Response>(request);
    }
}
