//HintName: CaravelleRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Caravelle
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            return services;
        }
    }

    // ── Typed Caravelle extension methods ──────────────────────────────
    public static class CaravelleExtensions
    {
    }
}
