//HintName: BeforeConventionPipelineHandlerDispatcher_614fbc5e.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class BeforeConventionPipelineHandlerDispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.BeforeConventionPipelineHandler.Request,
            BeforeConventionPipelineHandlerDispatcher.Result>
    {
        public sealed class Result : global::Caravelle.IDispatchResult
        {
            private Result() { }

            public Result(global::TestApp.BeforeConventionPipelineHandler.Response value)
            {
                if (value is null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }

                Value = value;
            }

            public Result(global::Caravelle.ValidationResult value)
            {
                if (value is null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }

                Value = value;
            }

            public object? Value { get; }

            public T Match<T>(
                global::System.Func<global::TestApp.BeforeConventionPipelineHandler.Response, T> onSuccess,
                global::System.Func<global::Caravelle.ValidationResult, T> onInvalid
            )
            {
                return Value switch
                {
                    global::TestApp.BeforeConventionPipelineHandler.Response value => onSuccess(value),
                    global::Caravelle.ValidationResult value => onInvalid(value),
                    _ => throw new global::System.InvalidOperationException("Unknown result value type.")
                };
            }
        }
        private readonly global::TestApp.BeforeConventionPipelineHandler _handler;

        public BeforeConventionPipelineHandlerDispatcher(global::TestApp.BeforeConventionPipelineHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.BeforeConventionPipelineHandler);

        public async global::System.Threading.Tasks.Task<Result>
            Handle(global::TestApp.BeforeConventionPipelineHandler.Request request)
        {
            var fromBeforeLoad = _handler.BeforeLoad(request);

            var fromNormalizeBefore = _handler.NormalizeBefore(fromBeforeLoad);

            var fromValidate = _handler.Validate(fromNormalizeBefore);
            if (fromValidate is global::Caravelle.IValidationResult fromValidateValidationResult && !fromValidateValidationResult.IsValid())
                return new Result(fromValidate);

            var fromHandle = await _handler.Handle(fromNormalizeBefore);
            return new Result(fromHandle);
        }
    }
}
