//HintName: CaravelleRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Caravelle
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.NonNullableValueTypeHandler>();
            services.AddTransient<
                global::Caravelle.IDispatcher<
                    global::TestApp.NonNullableValueTypeHandler.Request,
                    int>,
                global::TestApp.NonNullableValueTypeHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed Caravelle extension methods ──────────────────────────────
    public static class CaravelleExtensions
    {
        public static global::System.Threading.Tasks.Task<int>
            Handle(this global::Caravelle.Bus bus, global::TestApp.NonNullableValueTypeHandler.Request request)
            => bus.Handle<global::TestApp.NonNullableValueTypeHandler.Request, int>(request);
    }
}
