//HintName: HandlerTwoDispatcher_8d004a3a.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class HandlerTwoDispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.SharedRequest,
            global::TestApp.HandlerTwo.Response>
    {
        private readonly global::TestApp.HandlerTwo _handler;

        public HandlerTwoDispatcher(global::TestApp.HandlerTwo handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.HandlerTwo);

        public async global::System.Threading.Tasks.Task<global::TestApp.HandlerTwo.Response>
            Handle(global::TestApp.SharedRequest request)
        {
            var fromHandle = await _handler.Handle(request);
            return fromHandle;
        }
    }
}
