//HintName: HandlerOneDispatcher_a3fb6e0e.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class HandlerOneDispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.SharedRequest,
            global::TestApp.HandlerOne.Response>
    {
        private readonly global::TestApp.HandlerOne _handler;

        public HandlerOneDispatcher(global::TestApp.HandlerOne handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.HandlerOne);

        public async global::System.Threading.Tasks.Task<global::TestApp.HandlerOne.Response>
            Handle(global::TestApp.SharedRequest request)
        {
            var fromHandle = await _handler.Handle(request);
            return fromHandle;
        }
    }
}
