//HintName: NonNullableValueTypeHandlerDispatcher_8a11e9e5.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class NonNullableValueTypeHandlerDispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.NonNullableValueTypeHandler.Request,
            int>
    {
        private readonly global::TestApp.NonNullableValueTypeHandler _handler;

        public NonNullableValueTypeHandlerDispatcher(global::TestApp.NonNullableValueTypeHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.NonNullableValueTypeHandler);

        public global::System.Threading.Tasks.Task<int>
            Handle(global::TestApp.NonNullableValueTypeHandler.Request request)
        {
            var fromHandle = _handler.Handle(request);
            return global::System.Threading.Tasks.Task.FromResult(fromHandle);
        }
    }
}
