//HintName: CaravelleRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Caravelle
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.NullableHandleReturnHandler>();
            services.AddTransient<
                global::Caravelle.IDispatcher<
                    global::TestApp.NullableHandleReturnHandler.Request,
                    global::TestApp.NullableHandleReturnHandlerDispatcher.Result>,
                global::TestApp.NullableHandleReturnHandlerDispatcher>();
            return services;
        }
    }

    // ── Typed Caravelle extension methods ──────────────────────────────
    public static class CaravelleExtensions
    {
        public static global::System.Threading.Tasks.Task<global::TestApp.NullableHandleReturnHandlerDispatcher.Result>
            Handle(this global::Caravelle.Bus bus, global::TestApp.NullableHandleReturnHandler.Request request)
            => bus.Handle<global::TestApp.NullableHandleReturnHandler.Request, global::TestApp.NullableHandleReturnHandlerDispatcher.Result>(request);
    }
}
