//HintName: NullableHandleReturnHandlerDispatcher_c3bc60ec.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class NullableHandleReturnHandlerDispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.NullableHandleReturnHandler.Request,
            NullableHandleReturnHandlerDispatcher.Result>
    {
        public sealed class Result : global::Caravelle.IDispatchResult
        {
            private Result() { }

            public Result(global::TestApp.NullableHandleReturnHandler.Response value)
            {
                if (value is null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }

                Value = value;
            }

            public Result(global::Caravelle.NotFoundResult value)
            {
                if (value is null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }

                Value = value;
            }

            public object? Value { get; }

            public T Match<T>(
                global::System.Func<global::TestApp.NullableHandleReturnHandler.Response, T> onSuccess,
                global::System.Func<global::Caravelle.NotFoundResult, T> onNotFound
            )
            {
                return Value switch
                {
                    global::TestApp.NullableHandleReturnHandler.Response value => onSuccess(value),
                    global::Caravelle.NotFoundResult value => onNotFound(value),
                    _ => throw new global::System.InvalidOperationException("Unknown result value type.")
                };
            }
        }
        private readonly global::TestApp.NullableHandleReturnHandler _handler;

        public NullableHandleReturnHandlerDispatcher(global::TestApp.NullableHandleReturnHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.NullableHandleReturnHandler);

        public global::System.Threading.Tasks.Task<Result>
            Handle(global::TestApp.NullableHandleReturnHandler.Request request)
        {
            var fromHandle = _handler.Handle(request);
            if (fromHandle is not { } fromHandleValue)
                return global::System.Threading.Tasks.Task.FromResult(new Result(new global::Caravelle.NotFoundResult("response cannot be null")));
            var fromAfterAudit = _handler.AfterAudit(fromHandleValue);

            return global::System.Threading.Tasks.Task.FromResult(new Result(fromHandleValue));
        }
    }
}
