//HintName: CaravelleRegistrations.g.cs
// <auto-generated/>
#nullable enable

using Microsoft.Extensions.DependencyInjection;

namespace Caravelle
{
    public static class GeneratedHandlerRegistrations
    {
        public static IServiceCollection AddGeneratedHandlers(
            this IServiceCollection services)
        {
            services.AddTransient<global::TestApp.HandlerOne>();
            services.AddTransient<
                global::Caravelle.IDispatcher<
                    global::TestApp.SharedRequest,
                    global::TestApp.HandlerOne.Response>,
                global::TestApp.HandlerOneDispatcher>();
            services.AddTransient<global::TestApp.HandlerTwo>();
            services.AddTransient<
                global::Caravelle.IDispatcher<
                    global::TestApp.SharedRequest,
                    global::TestApp.HandlerTwo.Response>,
                global::TestApp.HandlerTwoDispatcher>();
            return services;
        }
    }

    // ── Typed Caravelle extension methods ──────────────────────────────
    public static class CaravelleExtensions
    {
    }
}
