//HintName: FullPipelineHandlerDispatcher_c3df660e.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class FullPipelineHandlerDispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.FullPipelineHandler.Request,
            FullPipelineHandlerDispatcher.Result>
    {
        public sealed class Result : global::Caravelle.IDispatchResult
        {
            private Result() { }

            public Result(global::TestApp.FullPipelineHandler.Response value)
            {
                if (value is null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }

                Value = value;
            }

            public Result(global::Caravelle.ValidationResult value)
            {
                if (value is null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }

                Value = value;
            }

            public Result(global::Caravelle.NotFoundResult value)
            {
                if (value is null)
                {
                    throw new global::System.ArgumentNullException(nameof(value));
                }

                Value = value;
            }

            public object? Value { get; }

            public T Match<T>(
                global::System.Func<global::TestApp.FullPipelineHandler.Response, T> onSuccess,
                global::System.Func<global::Caravelle.ValidationResult, T> onInvalid,
                global::System.Func<global::Caravelle.NotFoundResult, T> onNotFound
            )
            {
                return Value switch
                {
                    global::TestApp.FullPipelineHandler.Response value => onSuccess(value),
                    global::Caravelle.ValidationResult value => onInvalid(value),
                    global::Caravelle.NotFoundResult value => onNotFound(value),
                    _ => throw new global::System.InvalidOperationException("Unknown result value type.")
                };
            }
        }
        private readonly global::TestApp.FullPipelineHandler _handler;

        public FullPipelineHandlerDispatcher(global::TestApp.FullPipelineHandler handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.FullPipelineHandler);

        public async global::System.Threading.Tasks.Task<Result>
            Handle(global::TestApp.FullPipelineHandler.Request request)
        {
            var fromLoad = await _handler.Load(request);
            if (fromLoad is not { } fromLoadValue)
                return new Result(new global::Caravelle.NotFoundResult("entity cannot be null"));

            var fromValidate = _handler.Validate(fromLoadValue);
            if (fromValidate is global::Caravelle.IValidationResult fromValidateValidationResult && !fromValidateValidationResult.IsValid())
                return new Result(fromValidate);

            var fromHandle = await _handler.Handle(fromLoadValue);
            return new Result(fromHandle);
        }
    }
}
