//HintName: HandlerADispatcher_382a2177.g.cs
// <auto-generated/>
#nullable enable

namespace TestApp
{
    public sealed class HandlerADispatcher
        : global::Caravelle.IDispatcher<
            global::TestApp.HandlerA.Request,
            global::TestApp.HandlerA.Response>
    {
        private readonly global::TestApp.HandlerA _handler;

        public HandlerADispatcher(global::TestApp.HandlerA handler)
        {
            _handler = handler;
        }

        public string HandlerName => nameof(global::TestApp.HandlerA);

        public async global::System.Threading.Tasks.Task<global::TestApp.HandlerA.Response>
            Handle(global::TestApp.HandlerA.Request request)
        {
            var fromHandle = await _handler.Handle(request);
            return fromHandle;
        }
    }
}
