name: Publish NuGet

on:
  workflow_dispatch:
  push:
    tags:
      - v*

permissions:
  contents: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.ref }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release

      - name: Integration Tests
        run: pwsh ./Test-NugetPackage.ps1      

  publish:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.ref }}
          fetch-depth: 0
          filter: tree:0

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore

      - name: Pack
        run: dotnet pack Caravelle/Caravelle.csproj -c Release -o ./artifacts/nuget

      # Get a short-lived NuGet API key
      - name: NuGet login
        uses: NuGet/login@v1.2.0
        id: nuget-login
        with:
          user: ${{secrets.NUGET_USER}} 
            
      # Push the package
      - name: NuGet push
        run: dotnet nuget push ./artifacts/nuget/*.nupkg --api-key ${{steps.nuget-login.outputs.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --skip-duplicate

      - name: Create GitHub Release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${GITHUB_REF_NAME}" ./artifacts/nuget/*.nupkg ./artifacts/nuget/*.snupkg \
            --verify-tag \
            --generate-notes \
            --title "${GITHUB_REF_NAME}"